import { Puzzle } from "./types";

export const bishopPuzzles: Puzzle[] = [
  {
    id: "bishop-01",
    piece: "B",
    title: "Diagonal Dash",
    instruction: "Move the bishop to the star!",
    setup: [{ piece: "B", color: "w", square: "a1" }],
    targets: ["h8"],
    solution: ["h8"],
    maxMoves: 1,
    hints: ["The bishop moves diagonally.", "Go from corner to corner!"],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "bishop-02",
    piece: "B",
    title: "Other Way",
    instruction: "Move the bishop to the star!",
    setup: [{ piece: "B", color: "w", square: "h1" }],
    targets: ["a8"],
    solution: ["a8"],
    maxMoves: 1,
    hints: ["Bishops move diagonally in any direction."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "bishop-03",
    piece: "B",
    title: "Short Hop",
    instruction: "Move the bishop to the star!",
    setup: [{ piece: "B", color: "w", square: "d4" }],
    targets: ["f6"],
    solution: ["f6"],
    maxMoves: 1,
    hints: ["The bishop can move any number of squares diagonally."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "bishop-04",
    piece: "B",
    title: "Color Bound",
    instruction: "Reach the star! Notice the bishop stays on one color.",
    setup: [{ piece: "B", color: "w", square: "c1" }],
    targets: ["g5"],
    solution: ["g5"],
    maxMoves: 1,
    hints: ["A bishop always stays on the same color squares.", "c1 is a dark square, and so is g5."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "bishop-05",
    piece: "B",
    title: "Two Moves",
    instruction: "Reach the star in 2 moves!",
    setup: [{ piece: "B", color: "w", square: "a1" }],
    targets: ["a7"],
    solution: ["d4", "a7"],
    maxMoves: 3,
    hints: ["The bishop can't move in straight lines.", "Move to an intermediate diagonal, then redirect."],
    starThresholds: { three: 2, two: 2, one: 3 },
  },
  {
    id: "bishop-06",
    piece: "B",
    title: "Around the Block",
    instruction: "Navigate around the obstacle to the star!",
    setup: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "d4" },
    ],
    targets: ["g7"],
    solution: ["c3", "a5", "e1", "g3", "f4", "g5", "g7"],
    maxMoves: 5,
    hints: ["The pawn blocks the main diagonal.", "Try going to c3, then switch to a different diagonal."],
    starThresholds: { three: 4, two: 4, one: 5 },
  },
  {
    id: "bishop-07",
    piece: "B",
    title: "Capture!",
    instruction: "Capture the enemy knight!",
    setup: [
      { piece: "B", color: "w", square: "b2" },
      { piece: "N", color: "b", square: "f6" },
    ],
    targets: ["f6"],
    solution: ["f6"],
    maxMoves: 1,
    hints: ["The bishop captures by landing on the enemy's square."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "bishop-08",
    piece: "B",
    title: "Slalom",
    instruction: "Reach the star by weaving through the obstacles!",
    setup: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "g5" },
    ],
    targets: ["h8"],
    solution: ["b2", "a3", "f8", "g7", "h8"],
    maxMoves: 6,
    hints: ["The main diagonal is blocked.", "Try stepping to b2, then a3, then use the a3-f8 diagonal."],
    starThresholds: { three: 5, two: 5, one: 6 },
  },
  {
    id: "bishop-09",
    piece: "B",
    title: "Two Stars",
    instruction: "Reach both stars!",
    setup: [{ piece: "B", color: "w", square: "d4" }],
    targets: ["a1", "h8"],
    solution: ["a1", "h8"],
    maxMoves: 3,
    hints: ["Both stars are on the same diagonal!", "Visit one, then go to the other."],
    starThresholds: { three: 2, two: 2, one: 3 },
  },
  {
    id: "bishop-10",
    piece: "B",
    title: "Corridor",
    instruction: "Navigate through the gap to the star!",
    setup: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "b4" },
    ],
    targets: ["f8"],
    solution: ["c3", "a5", "f8"],
    maxMoves: 4,
    hints: ["Go to c3 first, avoiding the blocked diagonal.", "From a5, the diagonal to f8 is clear."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "bishop-11",
    piece: "B",
    title: "Capture and Go",
    instruction: "Capture the enemy rook, then reach the star!",
    setup: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "R", color: "b", square: "d4" },
    ],
    targets: ["d4", "g1"],
    solution: ["d4", "g1"],
    maxMoves: 3,
    hints: ["Capture the rook first.", "Then find a diagonal to the star."],
    starThresholds: { three: 2, two: 2, one: 3 },
  },
  {
    id: "bishop-12",
    piece: "B",
    title: "Zigzag Bishop",
    instruction: "Reach the star!",
    setup: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "c3" },
      { piece: "P", color: "w", square: "e5" },
    ],
    targets: ["g7"],
    solution: ["b2", "a3", "d6", "g3", "g7"],
    maxMoves: 6,
    hints: ["Both diagonals toward g7 are blocked.", "Zigzag around the pawns using short steps."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    id: "bishop-13",
    piece: "B",
    title: "Two Captures",
    instruction: "Capture both enemy pieces!",
    setup: [
      { piece: "B", color: "w", square: "d4" },
      { piece: "N", color: "b", square: "a7" },
      { piece: "R", color: "b", square: "g7" },
    ],
    targets: ["a7", "g7"],
    solution: ["a7", "d4", "g7"],
    maxMoves: 4,
    hints: ["Capture one, then reposition to capture the other.", "The knight is on the same diagonal."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "bishop-14",
    piece: "B",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    setup: [{ piece: "B", color: "w", square: "a1" }],
    targets: ["d4", "g7", "c7"],
    solution: ["d4", "g7", "e5", "c7"],
    maxMoves: 5,
    hints: ["d4 and g7 are on the same diagonal as a1.", "From g7, reposition to reach c7."],
    starThresholds: { three: 4, two: 4, one: 5 },
  },
  {
    id: "bishop-15",
    piece: "B",
    title: "Bishop Master",
    instruction: "Capture all enemies!",
    setup: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "P", color: "b", square: "c3" },
      { piece: "N", color: "b", square: "f6" },
    ],
    targets: ["c3", "f6"],
    solution: ["c3", "f6"],
    maxMoves: 3,
    hints: ["Both enemies are on the same long diagonal!", "Capture them in order."],
    starThresholds: { three: 2, two: 2, one: 3 },
  },
];
