import type { RoutePuzzle, FindMovesPuzzle } from "./types";

export const bishopPuzzles: (RoutePuzzle | FindMovesPuzzle)[] = [
  {
    type: "route",
    id: "bishop-01",
    playerPiece: "B",
    title: "Diagonal Dash",
    instruction: "Move the bishop to the star!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: [],
    stars: ["h8"],
    hints: ["The bishop moves diagonally.", "Go from corner to corner!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "bishop-02",
    playerPiece: "B",
    title: "Other Way",
    instruction: "Move the bishop to the star!",
    position: [{ piece: "B", color: "w", square: "h1" }],
    walls: [],
    stars: ["a8"],
    hints: ["Bishops move diagonally in any direction."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "bishop-03",
    playerPiece: "B",
    title: "Short Hop",
    instruction: "Move the bishop to the star!",
    position: [{ piece: "B", color: "w", square: "d4" }],
    walls: [],
    stars: ["f6"],
    hints: ["The bishop can move any number of squares diagonally."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "bishop-04",
    playerPiece: "B",
    title: "Color Bound",
    instruction: "Reach the star! Notice the bishop stays on one color.",
    position: [{ piece: "B", color: "w", square: "c1" }],
    walls: [],
    stars: ["g5"],
    hints: ["A bishop always stays on the same color squares.", "c1 is a dark square, and so is g5."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "bishop-05",
    playerPiece: "B",
    title: "Two Moves",
    instruction: "Reach the star in 2 moves!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: [],
    stars: ["a7"],
    hints: ["The bishop can't move in straight lines.", "Move to an intermediate diagonal, then redirect."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "bishop-06",
    playerPiece: "B",
    title: "Around the Block",
    instruction: "Navigate around the obstacle to the star!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: ["d4"],
    stars: ["g7"],
    hints: ["The pawn blocks the main diagonal.", "Try going to c3, then switch to a different diagonal."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "bishop-07",
    playerPiece: "B",
    title: "Capture!",
    instruction: "Capture the enemy knight!",
    position: [
      { piece: "B", color: "w", square: "b2" },
      { piece: "N", color: "b", square: "f6" },
    ],
    walls: [],
    stars: ["f6"],
    hints: ["The bishop captures by landing on the enemy's square."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "bishop-08",
    playerPiece: "B",
    title: "Slalom",
    instruction: "Reach the star by weaving through the obstacles!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: ["d4", "g5"],
    stars: ["h8"],
    hints: ["The main diagonal is blocked.", "Try stepping to b2, then a3, then use the a3-f8 diagonal."],
    starThresholds: { three: 5, two: 6, one: 7 },
  },
  {
    type: "route",
    id: "bishop-09",
    playerPiece: "B",
    title: "Two Stars",
    instruction: "Reach both stars!",
    position: [{ piece: "B", color: "w", square: "d4" }],
    walls: [],
    stars: ["a1", "h8"],
    hints: ["Both stars are on the same diagonal!", "Visit one, then go to the other."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "bishop-10",
    playerPiece: "B",
    title: "Corridor",
    instruction: "Navigate through the gap to the star!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: ["a4", "b4", "c4", "d4", "e4", "g4", "h4"],
    stars: ["f8"],
    hints: ["Go to c3 first, avoiding the blocked diagonal.", "From d2, we can launch through the gap."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "bishop-11",
    playerPiece: "B",
    title: "Capture and Go",
    instruction: "Capture the enemy rook, then reach the star!",
    position: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "R", color: "b", square: "d4" },
    ],
    walls: [],
    stars: ["d4", "g1"],
    hints: ["Capture the rook first.", "Then find a diagonal to the star."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "bishop-12",
    playerPiece: "B",
    title: "Zigzag Bishop",
    instruction: "Reach the star!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: ["c3", "e5"],
    stars: ["g7"],
    hints: ["Both diagonals toward g7 are blocked.", "Zigzag around the pawns using short steps."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "bishop-13",
    playerPiece: "B",
    title: "Two Captures",
    instruction: "Capture both enemy pieces!",
    position: [
      { piece: "B", color: "w", square: "d4" },
      { piece: "N", color: "b", square: "a7" },
      { piece: "R", color: "b", square: "g7" },
    ],
    walls: [],
    stars: ["a7", "g7"],
    hints: ["Capture one, then reposition to capture the other.", "The knight is on the same diagonal."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "bishop-14",
    playerPiece: "B",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    position: [{ piece: "B", color: "w", square: "a1" }],
    walls: [],
    stars: ["d4", "g7", "c7"],
    hints: ["d4 and g7 are on the same diagonal as a1.", "From g7, reposition to reach c7."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "bishop-15",
    playerPiece: "B",
    title: "Bishop Master",
    instruction: "Capture all enemies!",
    position: [
      { piece: "B", color: "w", square: "a1" },
      { piece: "P", color: "b", square: "c3" },
      { piece: "N", color: "b", square: "f6" },
    ],
    walls: [],
    stars: ["c3", "f6"],
    hints: ["Both enemies are on the same long diagonal!", "Capture them in order."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  // --- Find All Moves ---
  {
    type: "find-moves",
    id: "bishop-16",
    playerPiece: "B",
    title: "Find All Moves",
    instruction: "Click every square the bishop can move to!",
    position: [{ piece: "B", color: "w", square: "e4" }],
    walls: ["c2", "g6"],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
];
