import type { TacticPuzzle } from "./types";

export const castlingPuzzles: TacticPuzzle[] = [
  {
    type: "puzzle",
    id: "castling-01",
    title: "Kingside Castle",
    instruction: "Castle kingside! Move the king two squares toward the rook.",
    fen: "8/8/8/8/8/8/8/4K2R w K - 0 1",
    pgn: "1. O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-02",
    title: "Queenside Castle",
    instruction: "Castle queenside!",
    fen: "8/8/8/8/8/8/8/R3K3 w Q - 0 1",
    pgn: "1. O-O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-03",
    title: "Pick a Side",
    instruction: "You can castle either way — choose one!",
    fen: "8/8/8/8/8/8/8/R3K2R w KQ - 0 1",
    pgn: "1. O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-04",
    title: "Blocked Path",
    instruction: "Only one side is clear for castling. Find it!",
    fen: "8/8/8/8/8/8/8/RN2K2R w KQ - 0 1",
    pgn: "1. O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-05",
    title: "Danger Zone",
    instruction: "One castling side passes through an attacked square. Castle safely!",
    fen: "5r2/8/8/8/8/8/8/R3K2R w KQ - 0 1",
    pgn: "1. O-O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-06",
    title: "Under Fire",
    instruction: "You're in check! Can you castle?",
    fen: "4r3/8/8/8/8/8/8/4K2R w K - 0 1",
    pgn: "1. Kf1",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-07",
    title: "Castle & Protect",
    instruction: "Castle to get your king to safety!",
    fen: "3q4/8/8/8/8/8/5PPP/4K2R w K - 0 1",
    pgn: "1. O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-08",
    title: "No Castling Allowed",
    instruction: "Can you castle? If not, walk to safety!",
    fen: "8/8/b7/8/8/8/8/4K2R w K - 0 1",
    pgn: "1. Kd1",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-09",
    title: "Wrong Side Blocked",
    instruction: "Both rooks are ready, but only one side is safe. Choose wisely!",
    fen: "3r4/8/8/8/8/8/8/R3K2R w KQ - 0 1",
    pgn: "1. O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "puzzle",
    id: "castling-10",
    title: "Queenside Shelter",
    instruction: "Castle queenside to hide behind your pawns!",
    fen: "8/8/8/8/8/8/PPP5/R3K2R w Q - 0 1",
    pgn: "1. O-O-O",
    starThresholds: { three: 1, two: 2, one: 3 },
  },
];
