import { Puzzle } from "./types";

export const castlingPuzzles: Puzzle[] = [
  {
    id: "castling-01",
    piece: "K",
    title: "Kingside Castle",
    instruction: "Castle kingside! Move the king two squares toward the rook.",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "h1" },
    ],
    targets: ["g1"],
    solution: ["g1"],
    castlingRights: { K: true, Q: false, k: false, q: false },
    maxMoves: 1,
    hints: ["The king moves two squares toward the rook to castle.", "Click the king, then click g1."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-02",
    piece: "K",
    title: "Queenside Castle",
    instruction: "Castle queenside!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "a1" },
    ],
    targets: ["c1"],
    solution: ["c1"],
    castlingRights: { K: false, Q: true, k: false, q: false },
    maxMoves: 1,
    hints: ["Queenside castling moves the king to c1.", "The rook jumps over to d1."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-03",
    piece: "K",
    title: "Pick a Side",
    instruction: "You can castle either way — choose one!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "h1" },
    ],
    targets: ["g1"],
    solution: ["g1"],
    castlingRights: { K: true, Q: true, k: false, q: false },
    maxMoves: 1,
    hints: ["Both sides are open for castling.", "Kingside is g1, queenside is c1."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-04",
    piece: "K",
    title: "Blocked Path",
    instruction: "Only one side is clear for castling. Find it!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "P", color: "w", square: "b1" },
    ],
    targets: ["g1"],
    solution: ["g1"],
    castlingRights: { K: true, Q: true, k: false, q: false },
    maxMoves: 1,
    hints: ["You can't castle if pieces are between the king and rook.", "The queenside is blocked by the pawn on b1."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-05",
    piece: "K",
    title: "Danger Zone",
    instruction: "One castling side passes through an attacked square. Castle safely!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "R", color: "b", square: "f8" },
    ],
    targets: ["c1"],
    solution: ["c1"],
    castlingRights: { K: true, Q: true, k: false, q: false },
    maxMoves: 1,
    hints: [
      "You can't castle through check — the king can't pass through an attacked square.",
      "The black rook on f8 attacks f1, blocking kingside castling.",
      "Castle queenside instead!",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-06",
    piece: "K",
    title: "Under Fire",
    instruction: "You're in check! Can you castle?",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "R", color: "b", square: "e8" },
    ],
    targets: ["f1"],
    solution: ["f1"],
    castlingRights: { K: true, Q: false, k: false, q: false },
    maxMoves: 1,
    hints: [
      "You can't castle while in check!",
      "Move the king out of check first — or simply step aside.",
      "Move the king to f1 to escape.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-07",
    piece: "K",
    title: "Castle & Protect",
    instruction: "Castle to get your king to safety!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "P", color: "w", square: "f2" },
      { piece: "P", color: "w", square: "g2" },
      { piece: "P", color: "w", square: "h2" },
      { piece: "Q", color: "b", square: "d8" },
    ],
    targets: ["g1"],
    solution: ["g1"],
    castlingRights: { K: true, Q: false, k: false, q: false },
    maxMoves: 1,
    hints: [
      "Castling tucks the king behind pawns for safety.",
      "The pawns on f2, g2, h2 will shield the king after castling.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-08",
    piece: "K",
    title: "No Castling Allowed",
    instruction: "Can you castle? If not, walk to safety!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "B", color: "b", square: "a6" },
    ],
    targets: ["d1"],
    solution: ["d1"],
    castlingRights: { K: true, Q: false, k: false, q: false },
    maxMoves: 2,
    hints: [
      "The bishop on a6 attacks through to f1...",
      "The king can't pass through f1 because it's attacked.",
      "You can't castle! Step the king to safety instead.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "castling-09",
    piece: "K",
    title: "Wrong Side Blocked",
    instruction: "Both rooks are ready, but only one side is safe. Choose wisely!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "R", color: "b", square: "d8" },
    ],
    targets: ["g1"],
    solution: ["g1"],
    castlingRights: { K: true, Q: true, k: false, q: false },
    maxMoves: 1,
    hints: [
      "The black rook on d8 attacks d1.",
      "Queenside castling passes the king through d1 — that's attacked!",
      "Castle kingside to g1.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "castling-10",
    piece: "K",
    title: "Queenside Shelter",
    instruction: "Castle queenside to hide behind your pawns!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "R", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "a2" },
      { piece: "P", color: "w", square: "b2" },
      { piece: "P", color: "w", square: "c2" },
      { piece: "R", color: "b", square: "h1" },
    ],
    targets: ["c1"],
    solution: ["c1"],
    castlingRights: { K: false, Q: true, k: false, q: false },
    maxMoves: 1,
    hints: [
      "The enemy rook controls the h-file — kingside isn't available anyway.",
      "Castle queenside to tuck behind your a, b, c pawns.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
];
