import { Puzzle } from "./types";

export const checkmatePuzzles: Puzzle[] = [
  {
    id: "checkmate-01",
    piece: "R",
    title: "Back Rank Mate",
    instruction: "Deliver checkmate with the rook!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "R", color: "w", square: "a2" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "P", color: "b", square: "f7" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["a8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is trapped behind its own pawns.",
      "Deliver check on the back rank — the king has nowhere to go!",
      "Move the rook to a8.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-02",
    piece: "Q",
    title: "Queen's Kiss",
    instruction: "Deliver checkmate with the queen!",
    setup: [
      { piece: "K", color: "w", square: "f1" },
      { piece: "Q", color: "w", square: "d1" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["d8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is stuck in the corner with pawns blocking escape.",
      "Put the queen on the back rank to deliver checkmate.",
      "Move the queen to d8.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-03",
    piece: "Q",
    title: "Don't Stalemate!",
    instruction: "Checkmate — but be careful not to stalemate!",
    setup: [
      { piece: "K", color: "w", square: "f6" },
      { piece: "Q", color: "w", square: "a1" },
      { piece: "K", color: "b", square: "h8" },
    ],
    targets: [],
    solution: ["g7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "If the king has no legal moves AND isn't in check, it's stalemate (a draw).",
      "Don't play Qa8 — that's stalemate! The king would have no moves but no check.",
      "Move the queen to g7 for checkmate.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-04",
    piece: "R",
    title: "Rook Ladder",
    instruction: "Use the rook to deliver checkmate! The king is trapped on the edge.",
    setup: [
      { piece: "K", color: "w", square: "e6" },
      { piece: "R", color: "w", square: "a1" },
      { piece: "K", color: "b", square: "d8" },
    ],
    targets: [],
    solution: ["a8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The white king controls d7, e7, and f7.",
      "The black king is trapped on the back rank.",
      "Move the rook to a8 for checkmate.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-05",
    piece: "Q",
    title: "Cornered King",
    instruction: "Deliver checkmate with the queen — the rook cuts off escape!",
    setup: [
      { piece: "K", color: "w", square: "b6" },
      { piece: "Q", color: "w", square: "a4" },
      { piece: "R", color: "w", square: "b1" },
      { piece: "K", color: "b", square: "a8" },
      { piece: "P", color: "b", square: "a7" },
    ],
    targets: [],
    solution: ["a6"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is nearly trapped in the corner — a7 blocks one escape.",
      "Your king on b6 controls b7. The rook on b1 covers the b-file.",
      "Qa6 gives check — and there's nowhere to run!",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-06",
    piece: "N",
    title: "Smothered Mate",
    instruction: "Deliver checkmate with the knight!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "N", color: "w", square: "e5" },
      { piece: "Q", color: "w", square: "g6" },
      { piece: "K", color: "b", square: "g8" },
      { piece: "R", color: "b", square: "f8" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["f7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "A 'smothered mate' happens when the king is surrounded by its own pieces.",
      "The black king is boxed in by its rook and pawns.",
      "Move the knight to f7 for checkmate!",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-07",
    piece: "Q",
    title: "Scholar's Mate",
    instruction: "Deliver checkmate!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "Q", color: "w", square: "c4" },
      { piece: "B", color: "w", square: "c1" },
      { piece: "K", color: "b", square: "e8" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "P", color: "b", square: "e5" },
      { piece: "P", color: "b", square: "f7" },
    ],
    targets: [],
    solution: ["f7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The f7 square is only defended by the king.",
      "The queen can attack f7 and the bishop supports from c4's diagonal.",
      "Move the queen to f7 for checkmate! The king can't capture because the bishop defends.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-08",
    piece: "Q",
    title: "Stalemate Trap",
    instruction: "Checkmate in one — but watch out for stalemate!",
    setup: [
      { piece: "K", color: "w", square: "a6" },
      { piece: "Q", color: "w", square: "b4" },
      { piece: "K", color: "b", square: "a8" },
    ],
    targets: [],
    solution: ["b7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is almost trapped in the corner.",
      "Qb8 would be stalemate if it's not check! (Actually Qb8 IS check — but think about what gives checkmate.)",
      "Qb7 is checkmate — the queen covers all escape squares and the king on a6 guards b7.",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-09",
    piece: "R",
    title: "Support Mate",
    instruction: "Use your king to support the rook's checkmate!",
    setup: [
      { piece: "K", color: "w", square: "c7" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "K", color: "b", square: "a8" },
    ],
    targets: [],
    solution: ["a1"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The white king on c7 controls b7 and b8.",
      "Deliver check on the a-file — the king has no escape.",
      "Ra1 is checkmate!",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "checkmate-10",
    piece: "Q",
    title: "Queen & King Dance",
    instruction: "Find the one square that delivers checkmate!",
    setup: [
      { piece: "K", color: "w", square: "g6" },
      { piece: "Q", color: "w", square: "e4" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["e8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is boxed in the corner by its own pawns.",
      "The white king covers f7 and g7 (the pawn is there but the king also guards).",
      "Qe8 delivers check — and there are no escape squares!",
    ],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
];
