import { Puzzle } from "./types";

// === Back Rank Mates ===
export const backreakMatePuzzles: Puzzle[] = [
  {
    id: "checkmate-br-01",
    piece: "R",
    title: "Classic Back Rank",
    instruction: "The king is trapped behind its own pawns. Deliver checkmate!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "R", color: "w", square: "a2" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "P", color: "b", square: "f7" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["a8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is trapped behind its own pawns on the back rank.",
      "Move the rook to the 8th rank!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-br-02",
    piece: "Q",
    title: "Queen on the Back Rank",
    instruction: "Deliver checkmate with the queen on the back rank!",
    setup: [
      { piece: "K", color: "w", square: "f1" },
      { piece: "Q", color: "w", square: "d1" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["d8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The king is stuck in the corner with pawns blocking escape.",
      "Put the queen on the back rank — d8!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-br-03",
    piece: "R",
    title: "Back Rank with Support",
    instruction: "Deliver checkmate! Your king supports the rook.",
    setup: [
      { piece: "K", color: "w", square: "c7" },
      { piece: "R", color: "w", square: "h1" },
      { piece: "K", color: "b", square: "a8" },
    ],
    targets: [],
    solution: ["a1"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The white king on c7 controls b7 and b8.",
      "Deliver check on the a-file — the king has no escape.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-br-04",
    piece: "R",
    title: "Back Rank from Below",
    instruction: "Deliver checkmate with the rook!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "R", color: "w", square: "d1" },
      { piece: "K", color: "b", square: "b8" },
      { piece: "R", color: "b", square: "a7" },
      { piece: "P", color: "b", square: "b7" },
      { piece: "P", color: "b", square: "c7" },
    ],
    targets: [],
    solution: ["d8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The pawns on a7, b7, c7 block all the king's escape squares.",
      "Move the rook to the 8th rank!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-br-05",
    piece: "Q",
    title: "Don't Stalemate the Back Rank!",
    instruction: "Checkmate in one — but be careful not to stalemate!",
    setup: [
      { piece: "K", color: "w", square: "f6" },
      { piece: "Q", color: "w", square: "a1" },
      { piece: "K", color: "b", square: "h8" },
    ],
    targets: [],
    solution: ["g7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "If the king has no legal moves AND isn't in check, it's stalemate — a draw!",
      "Don't play Qa8 — that could be stalemate!",
      "Qg7 is checkmate — the king is in check with no escape.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
];

// === Smothered Mates ===
export const smotheredMatePuzzles: Puzzle[] = [
  {
    id: "checkmate-sm-01",
    piece: "N",
    title: "Classic Smother",
    instruction: "The king is trapped by its own pieces. Deliver checkmate with the knight!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "N", color: "w", square: "e5" },
      { piece: "Q", color: "w", square: "g6" },
      { piece: "K", color: "b", square: "g8" },
      { piece: "R", color: "b", square: "f8" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["f7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "A 'smothered mate' happens when the king is surrounded by its own pieces.",
      "The knight can jump over pieces — find the square that gives check!",
      "Nf7 is checkmate! The king is boxed in by its own rook and pawns.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-sm-02",
    piece: "N",
    title: "Corner Smother",
    instruction: "Deliver smothered mate in the corner!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "N", color: "w", square: "g5" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "R", color: "b", square: "g8" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["f7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The king on h8 is boxed in by its rook on g8 and pawn on h7.",
      "Find the knight move that gives check!",
      "Nf7 is checkmate!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-sm-03",
    piece: "N",
    title: "Knight Finds the Spot",
    instruction: "Only one knight move gives checkmate. Find it!",
    setup: [
      { piece: "K", color: "w", square: "g1" },
      { piece: "N", color: "w", square: "d5" },
      { piece: "K", color: "b", square: "g8" },
      { piece: "R", color: "b", square: "h8" },
      { piece: "B", color: "b", square: "f8" },
      { piece: "P", color: "b", square: "f7" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["e7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The king is surrounded by its own pieces.",
      "The knight on d5 can go to several squares — which one gives check?",
      "Ne7 gives check! And every escape square is blocked by black's own pieces.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
];

// === Rook Ladder (multi-move with random bot) ===
export const rookLadderPuzzles: Puzzle[] = [
  {
    id: "checkmate-rl-01",
    piece: "R",
    title: "Two-Rook Ladder",
    instruction: "Use your two rooks to push the king to the edge and deliver checkmate!",
    setup: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "a4" },
      { piece: "R", color: "w", square: "b3" },
      { piece: "K", color: "b", square: "e6" },
    ],
    targets: [],
    solution: [],
    mode: "checkmate-bot",
    hints: [
      "Rooks work as a team — one cuts off a rank, the other gives check on the next rank.",
      "Give check with one rook, then use the other to check on the next rank.",
      "Keep alternating rook checks to push the king to the edge!",
    ],
    starThresholds: { three: 4, two: 7, one: 12 },
  },
  {
    id: "checkmate-rl-02",
    piece: "R",
    title: "Ladder from the Side",
    instruction: "Push the king to the edge with alternating rook checks!",
    setup: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "c1" },
      { piece: "R", color: "w", square: "d2" },
      { piece: "K", color: "b", square: "f5" },
    ],
    targets: [],
    solution: [],
    mode: "checkmate-bot",
    hints: [
      "Cut off the king rank by rank, alternating your rooks.",
      "Give check, then bring the other rook up to the next rank.",
    ],
    starThresholds: { three: 5, two: 8, one: 14 },
  },
  {
    id: "checkmate-rl-03",
    piece: "R",
    title: "Almost There",
    instruction: "The king is near the edge — finish the ladder!",
    setup: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "R", color: "w", square: "a6" },
      { piece: "R", color: "w", square: "b5" },
      { piece: "K", color: "b", square: "d7" },
    ],
    targets: [],
    solution: [],
    mode: "checkmate-bot",
    hints: [
      "The king is already close to the back rank.",
      "Check with one rook, then deliver the final blow with the other!",
    ],
    starThresholds: { three: 3, two: 5, one: 8 },
  },
];

// === Queen + King Mates ===
export const queenKingMatePuzzles: Puzzle[] = [
  {
    id: "checkmate-qk-01",
    piece: "Q",
    title: "Cornered King",
    instruction: "Deliver checkmate with the queen — your king helps!",
    setup: [
      { piece: "K", color: "w", square: "b6" },
      { piece: "Q", color: "w", square: "a4" },
      { piece: "R", color: "w", square: "b1" },
      { piece: "K", color: "b", square: "a8" },
      { piece: "P", color: "b", square: "a7" },
    ],
    targets: [],
    solution: ["a6"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is nearly trapped — a7 blocks one escape.",
      "Your king on b6 controls b7. The rook covers the b-file.",
      "Qa6 is checkmate!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-qk-02",
    piece: "Q",
    title: "Queen & King Dance",
    instruction: "Find the one square that delivers checkmate!",
    setup: [
      { piece: "K", color: "w", square: "g6" },
      { piece: "Q", color: "w", square: "e4" },
      { piece: "K", color: "b", square: "h8" },
      { piece: "P", color: "b", square: "g7" },
      { piece: "P", color: "b", square: "h7" },
    ],
    targets: [],
    solution: ["e8"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is boxed in by its own pawns.",
      "The white king covers f7 and g7.",
      "Qe8 delivers check along the 8th rank — no escape!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-qk-03",
    piece: "Q",
    title: "Stalemate Trap!",
    instruction: "Checkmate in one — don't stalemate!",
    setup: [
      { piece: "K", color: "w", square: "a6" },
      { piece: "Q", color: "w", square: "b4" },
      { piece: "K", color: "b", square: "a8" },
    ],
    targets: [],
    solution: ["b7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The black king is almost trapped in the corner.",
      "Be careful — some queen moves leave the king with no legal moves but no check (stalemate)!",
      "Qb7 is checkmate — the queen covers all escape squares and delivers check.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "checkmate-qk-04",
    piece: "Q",
    title: "Scholar's Mate",
    instruction: "Deliver the famous Scholar's Mate!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "Q", color: "w", square: "c4" },
      { piece: "B", color: "w", square: "c1" },
      { piece: "K", color: "b", square: "e8" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "P", color: "b", square: "e5" },
      { piece: "P", color: "b", square: "f7" },
    ],
    targets: [],
    solution: ["f7"],
    mode: "checkmate",
    maxMoves: 1,
    hints: [
      "The f7 square is only defended by the king.",
      "The queen can attack f7 — and the bishop on c4's diagonal supports!",
      "Qxf7 is checkmate!",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
];
