import { Puzzle } from "./types";

export const enPassantPuzzles: Puzzle[] = [
  {
    id: "enpassant-01",
    piece: "P",
    title: "The Phantom Capture",
    instruction: "The black pawn just moved two squares! Capture it en passant!",
    setup: [
      { piece: "P", color: "w", square: "e5" },
      { piece: "P", color: "b", square: "d5" },
    ],
    enPassantSquare: "d6",
    targets: ["d6"],
    solution: ["d6"],
    maxMoves: 1,
    hints: [
      "When a pawn advances two squares and lands beside your pawn, you can capture it 'in passing'.",
      "Your pawn moves diagonally to d6, capturing the black pawn on d5.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-02",
    piece: "P",
    title: "Other Side",
    instruction: "The black pawn just advanced two squares past your pawn. Capture en passant!",
    setup: [
      { piece: "P", color: "w", square: "c5" },
      { piece: "P", color: "b", square: "d5" },
    ],
    enPassantSquare: "d6",
    targets: ["d6"],
    solution: ["d6"],
    maxMoves: 1,
    hints: [
      "En passant works from either side.",
      "Capture diagonally to d6 — the black pawn on d5 is removed.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-03",
    piece: "P",
    title: "Left or Right?",
    instruction: "Two black pawns are beside you, but only one just moved. Capture the right one!",
    setup: [
      { piece: "P", color: "w", square: "e5" },
      { piece: "P", color: "b", square: "d5" },
      { piece: "P", color: "b", square: "f5" },
    ],
    enPassantSquare: "f6",
    targets: ["f6"],
    solution: ["f6"],
    maxMoves: 1,
    hints: [
      "En passant only works on the pawn that JUST moved two squares.",
      "The en passant square is f6 — the pawn on f5 just arrived.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-04",
    piece: "P",
    title: "Now or Never",
    instruction: "Capture en passant — it's your only chance! (The option disappears next turn.)",
    setup: [
      { piece: "P", color: "w", square: "b5" },
      { piece: "P", color: "b", square: "a5" },
    ],
    enPassantSquare: "a6",
    targets: ["a6"],
    solution: ["a6"],
    maxMoves: 1,
    hints: [
      "En passant must be done immediately — you can't wait!",
      "Capture on a6 now before the chance disappears.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-05",
    piece: "P",
    title: "En Passant & Advance",
    instruction: "Capture en passant, then push your pawn to the star!",
    setup: [
      { piece: "P", color: "w", square: "g5" },
      { piece: "P", color: "b", square: "h5" },
    ],
    enPassantSquare: "h6",
    targets: ["h8"],
    solution: ["h6", "h7", "h8"],
    maxMoves: 4,
    hints: [
      "First capture en passant on h6.",
      "Then keep pushing the pawn forward to h8!",
    ],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "enpassant-06",
    piece: "P",
    title: "Clear the Path",
    instruction: "Use en passant to remove the blocker, then advance to the star!",
    setup: [
      { piece: "P", color: "w", square: "d5" },
      { piece: "P", color: "b", square: "c5" },
      { piece: "P", color: "w", square: "c4" },
    ],
    enPassantSquare: "c6",
    targets: ["c6"],
    solution: ["c6"],
    maxMoves: 1,
    hints: [
      "The black pawn on c5 is blocking your c4 pawn.",
      "Use your d5 pawn to capture en passant on c6, clearing the way.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-07",
    piece: "P",
    title: "Don't Fall for It",
    instruction: "The black pawn moved two squares, but en passant isn't the best move. Advance forward instead!",
    setup: [
      { piece: "P", color: "w", square: "d5" },
      { piece: "P", color: "b", square: "e5" },
    ],
    enPassantSquare: "e6",
    targets: ["d8"],
    solution: ["d6", "d7", "d8"],
    maxMoves: 4,
    hints: [
      "Just because you CAN capture en passant doesn't mean you should!",
      "Push your pawn straight ahead to reach the promotion square d8.",
    ],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "enpassant-08",
    piece: "P",
    title: "En Passant on the A-File",
    instruction: "Capture en passant on the edge of the board!",
    setup: [
      { piece: "P", color: "w", square: "b5" },
      { piece: "P", color: "b", square: "a5" },
    ],
    enPassantSquare: "a6",
    targets: ["a6"],
    solution: ["a6"],
    maxMoves: 1,
    hints: [
      "En passant works on any file, including the a-file.",
      "Capture diagonally to a6.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-09",
    piece: "P",
    title: "En Passant on the H-File",
    instruction: "Capture en passant on the edge of the board!",
    setup: [
      { piece: "P", color: "w", square: "g5" },
      { piece: "P", color: "b", square: "h5" },
    ],
    enPassantSquare: "h6",
    targets: ["h6"],
    solution: ["h6"],
    maxMoves: 1,
    hints: [
      "En passant works on the h-file too!",
      "Capture diagonally to h6.",
    ],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "enpassant-10",
    piece: "P",
    title: "Capture & Promote",
    instruction: "Capture en passant, then push all the way to promotion!",
    setup: [
      { piece: "P", color: "w", square: "c5" },
      { piece: "P", color: "b", square: "b5" },
    ],
    enPassantSquare: "b6",
    targets: ["b8"],
    solution: ["b6", "b7", "b8"],
    maxMoves: 4,
    hints: [
      "Capture en passant on b6 first.",
      "Then push the pawn forward to b7 and b8 to promote!",
    ],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "enpassant-11",
    piece: "P",
    title: "Not From Here!",
    instruction: "The black pawn just slid past yours! But en passant only works from the 5th rank — you're on the 6th. Push forward instead!",
    setup: [
      { piece: "P", color: "w", square: "e6" },
      { piece: "P", color: "b", square: "d5" },
    ],
    enPassantSquare: "d6",
    targets: ["e8"],
    solution: ["e7", "e8"],
    maxMoves: 3,
    hints: [
      "It looks tempting, but your pawn is too far advanced for en passant.",
      "En passant only works when your pawn is on the 5th rank (row 5 for white).",
      "Just push forward to e7 and e8!",
    ],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
];
