import type { RoutePuzzle } from "./types";

export const kingPuzzles: RoutePuzzle[] = [
  {
    type: "route",
    id: "king-01",
    playerPiece: "K",
    title: "One Step",
    instruction: "Move the king to the star!",
    position: [{ piece: "K", color: "w", square: "e4" }],
    walls: [],
    stars: ["e5"],
    hints: ["The king moves one square in any direction."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "king-02",
    playerPiece: "K",
    title: "Diagonal Step",
    instruction: "Move the king to the star!",
    position: [{ piece: "K", color: "w", square: "d4" }],
    walls: [],
    stars: ["e5"],
    hints: ["The king can also move diagonally — but only one square!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "king-03",
    playerPiece: "K",
    title: "Any Direction",
    instruction: "Move the king to the star!",
    position: [{ piece: "K", color: "w", square: "d4" }],
    walls: [],
    stars: ["c3"],
    hints: ["The king can move to any adjacent square — including backwards and sideways."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "king-04",
    playerPiece: "K",
    title: "Short Walk",
    instruction: "Walk the king to the star!",
    position: [{ piece: "K", color: "w", square: "a1" }],
    walls: [],
    stars: ["a4"],
    hints: ["The king can only move one square at a time.", "Be patient — walk straight up!"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-05",
    playerPiece: "K",
    title: "Diagonal Walk",
    instruction: "Walk the king to the star using diagonal steps!",
    position: [{ piece: "K", color: "w", square: "e1" }],
    walls: [],
    stars: ["h4"],
    hints: ["Diagonal moves cover both horizontal and vertical distance.", "Each diagonal step gets you closer in both directions."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-06",
    playerPiece: "K",
    title: "Capture!",
    instruction: "Capture the enemy pawn!",
    position: [
      { piece: "K", color: "w", square: "e4" },
      { piece: "P", color: "b", square: "f5" },
    ],
    walls: [],
    stars: ["f5"],
    hints: ["The king captures by moving to the enemy's square."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "king-07",
    playerPiece: "K",
    title: "Around the Wall",
    instruction: "Walk the king around the wall to the star!",
    position: [{ piece: "K", color: "w", square: "d1" }],
    walls: ["d2", "d3", "d4"],
    stars: ["d5"],
    hints: ["The king can't jump over pieces.", "Go around the wall of pawns."],
    starThresholds: { three: 5, two: 6, one: 7 },
  },
  {
    type: "route",
    id: "king-08",
    playerPiece: "K",
    title: "Shortest Path",
    instruction: "Reach the star in the fewest steps!",
    position: [{ piece: "K", color: "w", square: "a1" }],
    walls: [],
    stars: ["d4"],
    hints: ["Use diagonal moves to cover ground fastest.", "Each diagonal step gains one rank AND one file."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-09",
    playerPiece: "K",
    title: "Narrow Passage",
    instruction: "Guide the king through the gap!",
    position: [{ piece: "K", color: "w", square: "a1" }],
    walls: ["b3", "a3"],
    stars: ["a5"],
    hints: ["The direct path is blocked.", "Go diagonally around the pawns."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "king-10",
    playerPiece: "K",
    title: "Two Stars",
    instruction: "Visit both stars!",
    position: [{ piece: "K", color: "w", square: "d4" }],
    walls: [],
    stars: ["e5", "c3"],
    hints: ["The king can reach each star in one step.", "Visit one then walk back toward the other."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-11",
    playerPiece: "K",
    title: "Capture Walk",
    instruction: "Capture the enemy bishop, then reach the star!",
    position: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "B", color: "b", square: "f2" },
    ],
    walls: [],
    stars: ["h4"],
    hints: ["Capture the bishop — it's on your way!", "Then continue diagonally."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-12",
    playerPiece: "K",
    title: "Maze King",
    instruction: "Navigate through the pawns to the star!",
    position: [{ piece: "K", color: "w", square: "a1" }],
    walls: ["b1", "a2", "c2", "b3"],
    stars: ["c4"],
    hints: ["Find the one open path through the pawns.", "b2 is open!"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-13",
    playerPiece: "K",
    title: "Capture Spree",
    instruction: "Capture all three enemy pieces!",
    position: [
      { piece: "K", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "e5" },
      { piece: "P", color: "b", square: "e4" },
      { piece: "P", color: "b", square: "e3" },
    ],
    walls: [],
    stars: ["e5", "e4", "e3"],
    hints: ["The king can capture one per move.", "Capture them top to bottom (or bottom to top)."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "king-15",
    playerPiece: "K",
    title: "King Master",
    instruction: "Capture the enemies and reach the star!",
    position: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "P", color: "b", square: "b2" },
      { piece: "N", color: "b", square: "d4" },
    ],
    walls: [],
    stars: ["b2", "d4"],
    hints: ["Capture the pawn first — it's right next to you.", "Then walk diagonally to the knight."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
];
