import { Puzzle } from "./types";

export const kingPuzzles: Puzzle[] = [
  {
    id: "king-01",
    piece: "K",
    title: "One Step",
    instruction: "Move the king to the star!",
    setup: [{ piece: "K", color: "w", square: "e4" }],
    targets: ["e5"],
    solution: ["e5"],
    maxMoves: 1,
    hints: ["The king moves one square in any direction."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "king-02",
    piece: "K",
    title: "Diagonal Step",
    instruction: "Move the king to the star!",
    setup: [{ piece: "K", color: "w", square: "d4" }],
    targets: ["e5"],
    solution: ["e5"],
    maxMoves: 1,
    hints: ["The king can also move diagonally — but only one square!"],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "king-03",
    piece: "K",
    title: "Any Direction",
    instruction: "Move the king to the star!",
    setup: [{ piece: "K", color: "w", square: "d4" }],
    targets: ["c3"],
    solution: ["c3"],
    maxMoves: 1,
    hints: ["The king can move to any adjacent square — including backwards and sideways."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "king-04",
    piece: "K",
    title: "Short Walk",
    instruction: "Walk the king to the star!",
    setup: [{ piece: "K", color: "w", square: "a1" }],
    targets: ["a4"],
    solution: ["a2", "a3", "a4"],
    maxMoves: 4,
    hints: ["The king can only move one square at a time.", "Be patient — walk straight up!"],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-05",
    piece: "K",
    title: "Diagonal Walk",
    instruction: "Walk the king to the star using diagonal steps!",
    setup: [{ piece: "K", color: "w", square: "e1" }],
    targets: ["h4"],
    solution: ["f2", "g3", "h4"],
    maxMoves: 4,
    hints: ["Diagonal moves cover both horizontal and vertical distance.", "Each diagonal step gets you closer in both directions."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-06",
    piece: "K",
    title: "Capture!",
    instruction: "Capture the enemy pawn!",
    setup: [
      { piece: "K", color: "w", square: "e4" },
      { piece: "P", color: "b", square: "f5" },
    ],
    targets: ["f5"],
    solution: ["f5"],
    maxMoves: 1,
    hints: ["The king captures by moving to the enemy's square."],
    starThresholds: { three: 1, two: 1, one: 2 },
  },
  {
    id: "king-07",
    piece: "K",
    title: "Around the Wall",
    instruction: "Walk the king around the wall to the star!",
    setup: [
      { piece: "K", color: "w", square: "d1" },
      { piece: "P", color: "w", square: "d2" },
      { piece: "P", color: "w", square: "d3" },
      { piece: "P", color: "w", square: "d4" },
    ],
    targets: ["d5"],
    solution: ["e2", "e3", "e4", "e5", "d5"],
    maxMoves: 6,
    hints: ["The king can't jump over pieces.", "Go around the wall of pawns."],
    starThresholds: { three: 5, two: 5, one: 6 },
  },
  {
    id: "king-08",
    piece: "K",
    title: "Shortest Path",
    instruction: "Reach the star in the fewest steps!",
    setup: [{ piece: "K", color: "w", square: "a1" }],
    targets: ["d4"],
    solution: ["b2", "c3", "d4"],
    maxMoves: 4,
    hints: ["Use diagonal moves to cover ground fastest.", "Each diagonal step gains one rank AND one file."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-09",
    piece: "K",
    title: "Narrow Passage",
    instruction: "Guide the king through the gap!",
    setup: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "b3" },
      { piece: "P", color: "w", square: "a3" },
    ],
    targets: ["a5"],
    solution: ["b2", "c3", "b4", "a5"],
    maxMoves: 5,
    hints: ["The direct path is blocked.", "Go diagonally around the pawns."],
    starThresholds: { three: 4, two: 4, one: 5 },
  },
  {
    id: "king-10",
    piece: "K",
    title: "Two Stars",
    instruction: "Visit both stars!",
    setup: [{ piece: "K", color: "w", square: "d4" }],
    targets: ["e5", "c3"],
    solution: ["e5", "d4", "c3"],
    maxMoves: 4,
    hints: ["The king can reach each star in one step.", "Visit one then walk back toward the other."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-11",
    piece: "K",
    title: "Capture Walk",
    instruction: "Capture the enemy bishop, then reach the star!",
    setup: [
      { piece: "K", color: "w", square: "e1" },
      { piece: "B", color: "b", square: "f2" },
    ],
    targets: ["h4"],
    solution: ["f2", "g3", "h4"],
    maxMoves: 4,
    hints: ["Capture the bishop — it's on your way!", "Then continue diagonally."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-12",
    piece: "K",
    title: "Maze King",
    instruction: "Navigate through the pawns to the star!",
    setup: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "b1" },
      { piece: "P", color: "w", square: "a2" },
      { piece: "P", color: "w", square: "c2" },
      { piece: "P", color: "w", square: "b3" },
    ],
    targets: ["c4"],
    solution: ["b2", "c3", "c4"],
    maxMoves: 4,
    hints: ["Find the one open path through the pawns.", "b2 is open!"],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-13",
    piece: "K",
    title: "Capture Spree",
    instruction: "Capture all three enemy pieces!",
    setup: [
      { piece: "K", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "e5" },
      { piece: "P", color: "b", square: "e4" },
      { piece: "P", color: "b", square: "e3" },
    ],
    targets: ["e5", "e4", "e3"],
    solution: ["e5", "e4", "e3"],
    maxMoves: 4,
    hints: ["The king can capture one per move.", "Capture them top to bottom (or bottom to top)."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
  {
    id: "king-14",
    piece: "K",
    title: "Long Journey",
    instruction: "Walk the king to the far corner!",
    setup: [{ piece: "K", color: "w", square: "a1" }],
    targets: ["d4"],
    solution: ["b2", "c3", "d4"],
    maxMoves: 5,
    hints: ["Diagonal moves are the fastest way.", "You can reach d4 in just 3 diagonal steps!"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "king-15",
    piece: "K",
    title: "King Master",
    instruction: "Capture the enemies and reach the star!",
    setup: [
      { piece: "K", color: "w", square: "a1" },
      { piece: "P", color: "b", square: "b2" },
      { piece: "N", color: "b", square: "d4" },
    ],
    targets: ["b2", "d4"],
    solution: ["b2", "c3", "d4"],
    maxMoves: 4,
    hints: ["Capture the pawn first — it's right next to you.", "Then walk diagonally to the knight."],
    starThresholds: { three: 3, two: 3, one: 4 },
  },
];
