import type { RoutePuzzle } from "./types";

export const knightPuzzles: RoutePuzzle[] = [
  {
    type: "route",
    id: "knight-01",
    playerPiece: "N",
    title: "The L-Shape",
    instruction: "Move the knight to the star!",
    position: [{ piece: "N", color: "w", square: "d4" }],
    walls: [],
    stars: ["f5"],
    hints: ["The knight moves in an L-shape: 2 squares one way, then 1 square perpendicular.", "Try 2 right + 1 up."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "knight-02",
    playerPiece: "N",
    title: "Other L",
    instruction: "Move the knight to the star!",
    position: [{ piece: "N", color: "w", square: "d4" }],
    walls: [],
    stars: ["e6"],
    hints: ["The L can go in any direction.", "Try 1 right + 2 up."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "knight-03",
    playerPiece: "N",
    title: "Backwards L",
    instruction: "Move the knight to the star!",
    position: [{ piece: "N", color: "w", square: "e5" }],
    walls: [],
    stars: ["c4"],
    hints: ["The knight can also move in L-shapes going left and down."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "knight-04",
    playerPiece: "N",
    title: "Jump!",
    instruction: "Jump over the pawns to the star!",
    position: [{ piece: "N", color: "w", square: "d4" }],
    walls: ["d5", "e4", "e5", "d3", "c4"],
    stars: ["f5"],
    hints: ["The knight is the only piece that can jump over others!", "The pawns don't block the knight."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "knight-05",
    playerPiece: "N",
    title: "Two Hops",
    instruction: "Reach the star in 2 moves!",
    position: [{ piece: "N", color: "w", square: "b1" }],
    walls: [],
    stars: ["e4"],
    hints: ["Plan two L-shaped jumps.", "Where can you land after one jump that reaches e4 next?"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "knight-06",
    playerPiece: "N",
    title: "Capture!",
    instruction: "Capture the enemy bishop!",
    position: [
      { piece: "N", color: "w", square: "d4" },
      { piece: "B", color: "b", square: "f5" },
    ],
    walls: [],
    stars: ["f5"],
    hints: ["The knight captures by landing on the enemy's square."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "knight-07",
    playerPiece: "N",
    title: "Color Switch",
    instruction: "Reach the star! Notice the knight changes square color each move.",
    position: [{ piece: "N", color: "w", square: "a1" }],
    walls: [],
    stars: ["b3"],
    hints: ["a1 is a dark square, b3 is a light square.", "The knight always lands on the opposite color!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "knight-08",
    playerPiece: "N",
    title: "Corner Escape",
    instruction: "The knight is in the corner. Reach the star!",
    position: [{ piece: "N", color: "w", square: "a1" }],
    walls: [],
    stars: ["d4"],
    hints: ["From the corner, the knight only has 2 possible moves.", "Jump to b3 or c2 first."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "knight-09",
    playerPiece: "N",
    title: "Knight's Tour",
    instruction: "Visit both stars!",
    position: [{ piece: "N", color: "w", square: "d4" }],
    walls: [],
    stars: ["f5", "g3"],
    hints: ["Visit one star, then jump to the other.", "f5 to g3 is a valid L-shape!"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "knight-10",
    playerPiece: "N",
    title: "Jump the Wall",
    instruction: "Jump over the wall of pawns to the star!",
    position: [{ piece: "N", color: "w", square: "d1" }],
    walls: ["a3", "b3", "c3", "d3", "e3", "f3", "g3", "h3"],
    stars: ["e5"],
    hints: ["The knight can jump over the entire wall!", "Move sideways first, then leap over."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "knight-11",
    playerPiece: "N",
    title: "Zigzag Knight",
    instruction: "Reach the star!",
    position: [{ piece: "N", color: "w", square: "a1" }],
    walls: [],
    stars: ["g7"],
    hints: ["The knight zigzags across the board.", "Each jump covers ground diagonally."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "knight-12",
    playerPiece: "N",
    title: "Capture Path",
    instruction: "Capture the enemy rook, then reach the star!",
    position: [
      { piece: "N", color: "w", square: "b1" },
      { piece: "R", color: "b", square: "c3" },
    ],
    walls: [],
    stars: ["c3", "e4"],
    hints: ["Capture the rook first.", "Then one more jump to the star."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "knight-13",
    playerPiece: "N",
    title: "Three Stars",
    instruction: "Visit all three stars!",
    position: [{ piece: "N", color: "w", square: "d4" }],
    walls: [],
    stars: ["f5", "e3", "c2"],
    hints: ["Each star is one L-shaped jump from the previous!", "Chain your jumps together."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "knight-14",
    playerPiece: "N",
    title: "Capture Trio",
    instruction: "Capture all three enemy pieces!",
    position: [
      { piece: "N", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "f5" },
      { piece: "P", color: "b", square: "e3" },
      { piece: "B", color: "b", square: "c2" },
    ],
    walls: [],
    stars: ["f5", "e3", "c2"],
    hints: ["Capture them in the right order.", "Each hop should set up the next capture."],
    starThresholds: { three: 3, two: 4, one: 7 },
  },
  {
    type: "route",
    id: "knight-15",
    playerPiece: "N",
    title: "Knight Master",
    instruction: "Capture all enemies — the knight can jump over everything!",
    position: [
      { piece: "N", color: "w", square: "a1" },
      { piece: "P", color: "b", square: "b3" },
      { piece: "N", color: "b", square: "d4" },
    ],
    walls: ["b1", "a2"],
    stars: ["b3", "d4"],
    hints: ["The friendly pawns don't block the knight's jumps.", "Capture b3 first, then jump to d4."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
];
