import { Puzzle } from "./types";

export const knightPuzzles: Puzzle[] = [
  {
    id: "knight-01",
    piece: "N",
    title: "The L-Shape",
    instruction: "Move the knight to the star!",
    setup: [{ piece: "N", color: "w", square: "d4" }],
    targets: ["f5"],
    solution: ["f5"],
    maxMoves: 1,
    hints: ["The knight moves in an L-shape: 2 squares one way, then 1 square perpendicular.", "Try 2 right + 1 up."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "knight-02",
    piece: "N",
    title: "Other L",
    instruction: "Move the knight to the star!",
    setup: [{ piece: "N", color: "w", square: "d4" }],
    targets: ["e6"],
    solution: ["e6"],
    maxMoves: 1,
    hints: ["The L can go in any direction.", "Try 1 right + 2 up."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "knight-03",
    piece: "N",
    title: "Backwards L",
    instruction: "Move the knight to the star!",
    setup: [{ piece: "N", color: "w", square: "e5" }],
    targets: ["c4"],
    solution: ["c4"],
    maxMoves: 1,
    hints: ["The knight can also move in L-shapes going left and down."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "knight-04",
    piece: "N",
    title: "Jump!",
    instruction: "Jump over the pawns to the star!",
    setup: [
      { piece: "N", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "d5" },
      { piece: "P", color: "w", square: "e4" },
      { piece: "P", color: "w", square: "e5" },
      { piece: "P", color: "w", square: "d3" },
      { piece: "P", color: "w", square: "c4" },
    ],
    targets: ["f5"],
    solution: ["f5"],
    maxMoves: 1,
    hints: ["The knight is the only piece that can jump over others!", "The pawns don't block the knight."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "knight-05",
    piece: "N",
    title: "Two Hops",
    instruction: "Reach the star in 2 moves!",
    setup: [{ piece: "N", color: "w", square: "b1" }],
    targets: ["e4"],
    solution: ["c3", "e4"],
    maxMoves: 3,
    hints: ["Plan two L-shaped jumps.", "Where can you land after one jump that reaches e4 next?"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "knight-06",
    piece: "N",
    title: "Capture!",
    instruction: "Capture the enemy bishop!",
    setup: [
      { piece: "N", color: "w", square: "d4" },
      { piece: "B", color: "b", square: "f5" },
    ],
    targets: ["f5"],
    solution: ["f5"],
    maxMoves: 1,
    hints: ["The knight captures by landing on the enemy's square."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "knight-07",
    piece: "N",
    title: "Color Switch",
    instruction: "Reach the star! Notice the knight changes square color each move.",
    setup: [{ piece: "N", color: "w", square: "a1" }],
    targets: ["b3"],
    solution: ["b3"],
    maxMoves: 1,
    hints: ["a1 is a dark square, b3 is a light square.", "The knight always lands on the opposite color!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "knight-08",
    piece: "N",
    title: "Corner Escape",
    instruction: "The knight is in the corner. Reach the star!",
    setup: [{ piece: "N", color: "w", square: "a1" }],
    targets: ["d4"],
    solution: ["b3", "d4"],
    maxMoves: 3,
    hints: ["From the corner, the knight only has 2 possible moves.", "Jump to b3 or c2 first."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "knight-09",
    piece: "N",
    title: "Knight's Tour",
    instruction: "Visit both stars!",
    setup: [{ piece: "N", color: "w", square: "d4" }],
    targets: ["f5", "g3"],
    solution: ["f5", "g3"],
    maxMoves: 3,
    hints: ["Visit one star, then jump to the other.", "f5 to g3 is a valid L-shape!"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "knight-10",
    piece: "N",
    title: "Jump the Wall",
    instruction: "Jump over the wall of pawns to the star!",
    setup: [
      { piece: "N", color: "w", square: "d1" },
      { piece: "P", color: "w", square: "a3" },
      { piece: "P", color: "w", square: "b3" },
      { piece: "P", color: "w", square: "c3" },
      { piece: "P", color: "w", square: "d3" },
      { piece: "P", color: "w", square: "e3" },
      { piece: "P", color: "w", square: "f3" },
      { piece: "P", color: "w", square: "g3" },
      { piece: "P", color: "w", square: "h3" },
    ],
    targets: ["e5"],
    solution: ["f2", "g4", "e5"],
    maxMoves: 4,
    hints: ["The knight can jump over the entire wall!", "Move sideways first, then leap over."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "knight-11",
    piece: "N",
    title: "Zigzag Knight",
    instruction: "Reach the star!",
    setup: [{ piece: "N", color: "w", square: "a1" }],
    targets: ["g7"],
    solution: ["b3", "d4", "f5", "g7"],
    maxMoves: 5,
    hints: ["The knight zigzags across the board.", "Each jump covers ground diagonally."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    id: "knight-12",
    piece: "N",
    title: "Capture Path",
    instruction: "Capture the enemy rook, then reach the star!",
    setup: [
      { piece: "N", color: "w", square: "b1" },
      { piece: "R", color: "b", square: "c3" },
    ],
    targets: ["c3", "e4"],
    solution: ["c3", "e4"],
    maxMoves: 3,
    hints: ["Capture the rook first.", "Then one more jump to the star."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "knight-13",
    piece: "N",
    title: "Three Stars",
    instruction: "Visit all three stars!",
    setup: [{ piece: "N", color: "w", square: "d4" }],
    targets: ["f5", "e3", "c2"],
    solution: ["f5", "e3", "c2"],
    maxMoves: 4,
    hints: ["Each star is one L-shaped jump from the previous!", "Chain your jumps together."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "knight-14",
    piece: "N",
    title: "Capture Trio",
    instruction: "Capture all three enemy pieces!",
    setup: [
      { piece: "N", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "f5" },
      { piece: "P", color: "b", square: "e3" },
      { piece: "B", color: "b", square: "c1" },
    ],
    targets: ["f5", "e3", "c1"],
    solution: ["f5", "e3", "c1"],
    maxMoves: 4,
    hints: ["Capture them in the right order.", "Each capture should set up the next jump."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "knight-15",
    piece: "N",
    title: "Knight Master",
    instruction: "Capture all enemies — the knight can jump over everything!",
    setup: [
      { piece: "N", color: "w", square: "a1" },
      { piece: "P", color: "b", square: "b3" },
      { piece: "N", color: "b", square: "d4" },
      { piece: "P", color: "w", square: "b1" },
      { piece: "P", color: "w", square: "a2" },
    ],
    targets: ["b3", "d4"],
    solution: ["b3", "d4"],
    maxMoves: 3,
    hints: ["The friendly pawns don't block the knight's jumps.", "Capture b3 first, then jump to d4."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
];
