import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessDiscoveredPuzzles: Puzzle[] = [
  {
    id: "lichess-disc-01",
    piece: "K",
    title: "Discovered Attack #1",
    instruction: "Move one piece to unleash another!",
    setup: "1r6/3R4/3K4/8/3k4/8/8/8 w - - 64 92",
    targets: ["c7", "b8"] as SquareId[],
    solution: ["c7", "b8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d4" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-02",
    piece: "K",
    title: "Discovered Attack #2",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/5k2/8/5K2/5R2/7r w - - 38 93",
    targets: ["g2", "h1"] as SquareId[],
    solution: ["g2", "h1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-03",
    piece: "K",
    title: "Discovered Attack #3",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/r7/8/1RK1k3/8/8/8 w - - 8 67",
    targets: ["b5", "a6"] as SquareId[],
    solution: ["b5", "a6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e4" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-04",
    piece: "K",
    title: "Discovered Attack #4",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/8/3k1KR1/8/7r/8 w - - 41 76",
    targets: ["g3", "h2"] as SquareId[],
    solution: ["g3", "h2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d4" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-05",
    piece: "K",
    title: "Discovered Attack #5",
    instruction: "Move one piece to unleash another!",
    setup: "8/1r6/8/2RK1k2/8/8/8/8 w - - 9 70",
    targets: ["c6", "b7"] as SquareId[],
    solution: ["c6", "b7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-06",
    piece: "K",
    title: "Discovered Attack #6",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/8/1RK1k3/8/r7/8 w - - 37 119",
    targets: ["b3", "a2"] as SquareId[],
    solution: ["b3", "a2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e4" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-07",
    piece: "P",
    title: "Discovered Attack #7",
    instruction: "Move one piece to unleash another!",
    setup: "8/6B1/r4P2/4k1K1/8/8/8/8 w - - 3 69",
    targets: ["f7", "f8"] as SquareId[],
    solution: ["f7", "f8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e5" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-08",
    piece: "K",
    title: "Discovered Attack #8",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/4rp2/8/1k1K1R2/8/8 w - - 6 59",
    targets: ["d4", "e5"] as SquareId[],
    solution: ["d4", "e5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "b3" as SquareId, to: "b4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-09",
    piece: "K",
    title: "Discovered Attack #9",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/r7/8/8/8/7p/2R2K1k w - - 4 81",
    targets: ["f2"] as SquareId[],
    solution: ["f2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
  },
  {
    id: "lichess-disc-10",
    piece: "K",
    title: "Discovered Attack #10",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/1RK1k3/8/r7/8/8/8 w - - 0 54",
    targets: ["b5", "a4"] as SquareId[],
    solution: ["b5", "a4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e6" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-11",
    piece: "K",
    title: "Discovered Attack #11",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/8/1RK1k3/8/r7/8 w - - 0 59",
    targets: ["b3", "a2"] as SquareId[],
    solution: ["b3", "a2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e4" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-12",
    piece: "N",
    title: "Discovered Attack #12",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/5K2/3N4/8/7R/k7/1q6 w - - 2 81",
    targets: ["c3", "b1"] as SquareId[],
    solution: ["c3", "b1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "a2" as SquareId, to: "b3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-13",
    piece: "K",
    title: "Discovered Attack #13",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/5k1p/8/5K2/5R2/7r w - - 0 95",
    targets: ["g2", "h1"] as SquareId[],
    solution: ["g2", "h1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-14",
    piece: "K",
    title: "Discovered Attack #14",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/1R2K2k/6p1/2r5/8/8/8 w - - 2 72",
    targets: ["d5", "c4"] as SquareId[],
    solution: ["d5", "c4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h6" as SquareId, to: "h5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-15",
    piece: "N",
    title: "Discovered Attack #15",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/3q1k2/8/8/6NK/4R3/8 w - - 1 64",
    targets: ["e4", "d6"] as SquareId[],
    solution: ["e4", "d6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f6" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-16",
    piece: "K",
    title: "Discovered Attack #16",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/1RK1k3/8/r7/8/8/8 w - - 0 51",
    targets: ["b5", "a4"] as SquareId[],
    solution: ["b5", "a4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e6" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-17",
    piece: "P",
    title: "Discovered Attack #17",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/5q2/7p/3RP2k/3K4/8/8 w - - 6 52",
    targets: ["e5", "f6"] as SquareId[],
    solution: ["e5", "f6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h4" as SquareId, to: "g5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-18",
    piece: "P",
    title: "Discovered Attack #18",
    instruction: "Move one piece to unleash another!",
    setup: "8/3B4/8/5P2/6kP/2r5/6K1/8 w - - 7 65",
    targets: ["f6", "f7"] as SquareId[],
    solution: ["f6", "f7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g4" as SquareId, to: "h4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-19",
    piece: "P",
    title: "Discovered Attack #19",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/1pK5/8/R1P1k3/1r6/8/8 w - - 1 54",
    targets: ["c5", "b6"] as SquareId[],
    solution: ["c5", "b6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e4" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-20",
    piece: "K",
    title: "Discovered Attack #20",
    instruction: "Move one piece to unleash another!",
    setup: "8/6pk/8/8/5r2/7K/7R/8 w - - 0 57",
    targets: ["g3", "f4"] as SquareId[],
    solution: ["g3", "f4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h7" as SquareId, to: "g6" as SquareId }],
    strictSolution: true,
  },
];
