import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessMateIn2Puzzles: Puzzle[] = [
  {
    id: "lichess-m2-01",
    piece: "Q",
    title: "Mate in 2 #1",
    instruction: "Find the two-move checkmate!",
    setup: "2r3k1/5ppp/8/1q1p4/1p1P4/4PKP1/2Q2P2/8 w - - 0 32",
    targets: [] as SquareId[],
    solution: ["c8", "e8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "b5" as SquareId, to: "e8" as SquareId }],
  },
  {
    id: "lichess-m2-02",
    piece: "R",
    title: "Mate in 2 #2",
    instruction: "Find the two-move checkmate!",
    setup: "4q2k/ppp3pp/8/6r1/2N3P1/6nP/PP3r2/2R1R1K1 w - - 0 25",
    targets: [] as SquareId[],
    solution: ["e8", "f8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "f2" as SquareId, to: "f8" as SquareId }],
  },
  {
    id: "lichess-m2-03",
    piece: "R",
    title: "Mate in 2 #3",
    instruction: "Find the two-move checkmate!",
    setup: "2r3k1/1b3p1p/3Rp1pB/p6n/4P3/1Bb2P2/PrP3PP/3R2K1 w - - 2 25",
    targets: [] as SquareId[],
    solution: ["d8", "d8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "c8" as SquareId, to: "d8" as SquareId }],
  },
  {
    id: "lichess-m2-04",
    piece: "R",
    title: "Mate in 2 #4",
    instruction: "Find the two-move checkmate!",
    setup: "7k/7p/R6K/1p5p/1P1r4/5P2/5b2/8 w - - 0 49",
    targets: [] as SquareId[],
    solution: ["a8", "d8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "d4" as SquareId, to: "d8" as SquareId }],
  },
  {
    id: "lichess-m2-05",
    piece: "Q",
    title: "Mate in 2 #5",
    instruction: "Find the two-move checkmate!",
    setup: "2r3k1/p3qp1p/4p1pQ/8/4p2R/PP6/2r2PPP/4R1K1 w - - 2 25",
    targets: [] as SquareId[],
    solution: ["h7", "h8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "f8" as SquareId }],
  },
  {
    id: "lichess-m2-06",
    piece: "R",
    title: "Mate in 2 #6",
    instruction: "Find the two-move checkmate!",
    setup: "6k1/p1p2pp1/7p/8/3rB3/P1r3P1/5P1P/1R4K1 w - - 3 28",
    targets: [] as SquareId[],
    solution: ["b8", "d8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "d4" as SquareId, to: "d8" as SquareId }],
  },
  {
    id: "lichess-m2-07",
    piece: "B",
    title: "Mate in 2 #7",
    instruction: "Find the two-move checkmate!",
    setup: "rn1qkbnr/pp2p2b/2p1Pp2/3p1p2/3P2B1/2N5/PPP4P/R1BQK1NR w KQkq - 0 11",
    targets: [] as SquareId[],
    solution: ["h5", "g6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "h7" as SquareId, to: "g6" as SquareId }],
  },
  {
    id: "lichess-m2-08",
    piece: "R",
    title: "Mate in 2 #8",
    instruction: "Find the two-move checkmate!",
    setup: "6k1/p1p2pp1/1p3n1p/2n5/2q4P/2P3P1/P1Q3K1/3RN3 w - - 0 29",
    targets: [] as SquareId[],
    solution: ["d8", "e8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "f6" as SquareId, to: "e8" as SquareId }],
  },
  {
    id: "lichess-m2-09",
    piece: "Q",
    title: "Mate in 2 #9",
    instruction: "Find the two-move checkmate!",
    setup: "r5kn/1p2qpp1/p7/2p3P1/P2p1PP1/3Q4/1PP1r3/2K4R w - - 0 29",
    targets: [] as SquareId[],
    solution: ["h7", "h8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "f8" as SquareId }],
  },
  {
    id: "lichess-m2-10",
    piece: "Q",
    title: "Mate in 2 #10",
    instruction: "Find the two-move checkmate!",
    setup: "r5k1/4Qp2/1rb2Kp1/4p1P1/4P3/8/5PB1/8 w - - 0 53",
    targets: [] as SquareId[],
    solution: ["f7", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
  },
  {
    id: "lichess-m2-11",
    piece: "Q",
    title: "Mate in 2 #11",
    instruction: "Find the two-move checkmate!",
    setup: "r1r3k1/p2R1pp1/1p2p2p/8/8/4q3/P1P3PP/3R1Q1K w - - 0 27",
    targets: [] as SquareId[],
    solution: ["f7", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
  },
  {
    id: "lichess-m2-12",
    piece: "R",
    title: "Mate in 2 #12",
    instruction: "Find the two-move checkmate!",
    setup: "6k1/pp4pp/4p2r/3pn1q1/1P6/P3PQ1P/1B4PK/2R5 w - - 0 23",
    targets: [] as SquareId[],
    solution: ["c8", "d8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g5" as SquareId, to: "d8" as SquareId }],
  },
  {
    id: "lichess-m2-13",
    piece: "Q",
    title: "Mate in 2 #13",
    instruction: "Find the two-move checkmate!",
    setup: "rr1q2k1/2R2pbp/4p1p1/p7/3P1Q2/5N2/5PPP/2R3K1 w - - 0 24",
    targets: [] as SquareId[],
    solution: ["f7", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
  },
  {
    id: "lichess-m2-14",
    piece: "Q",
    title: "Mate in 2 #14",
    instruction: "Find the two-move checkmate!",
    setup: "2r3k1/R4pp1/8/2q4Q/6PK/2r4P/P7/8 w - - 1 32",
    targets: [] as SquareId[],
    solution: ["f7", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
  },
  {
    id: "lichess-m2-15",
    piece: "Q",
    title: "Mate in 2 #15",
    instruction: "Find the two-move checkmate!",
    setup: "r2q3k/2p1bp2/p7/1pnn1N2/4pQ2/6P1/PPPN1P2/2K5 w - - 0 28",
    targets: [] as SquareId[],
    solution: ["h6", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "h8" as SquareId, to: "g8" as SquareId }],
  },
  {
    id: "lichess-m2-16",
    piece: "Q",
    title: "Mate in 2 #16",
    instruction: "Find the two-move checkmate!",
    setup: "8/6pp/1p3r1k/4p3/4Q3/4p2P/3qB1K1/8 w - - 10 38",
    targets: [] as SquareId[],
    solution: ["h4", "h5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "h6" as SquareId, to: "g6" as SquareId }],
  },
  {
    id: "lichess-m2-17",
    piece: "Q",
    title: "Mate in 2 #17",
    instruction: "Find the two-move checkmate!",
    setup: "4Qbk1/p7/6B1/1p2p3/1qp3PK/8/8/8 w - - 0 44",
    targets: [] as SquareId[],
    solution: ["f7", "h7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
  },
  {
    id: "lichess-m2-18",
    piece: "R",
    title: "Mate in 2 #18",
    instruction: "Find the two-move checkmate!",
    setup: "6k1/r2R1rpp/8/8/3b4/6P1/P5KP/5R2 w - - 0 31",
    targets: [] as SquareId[],
    solution: ["d8", "f8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "f7" as SquareId, to: "f8" as SquareId }],
  },
  {
    id: "lichess-m2-19",
    piece: "Q",
    title: "Mate in 2 #19",
    instruction: "Find the two-move checkmate!",
    setup: "2r1q2k/p6p/1pQ2ppB/8/8/3P1P1P/P1P2P2/6K1 w - - 0 21",
    targets: [] as SquareId[],
    solution: ["f6", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "h8" as SquareId, to: "g8" as SquareId }],
  },
  {
    id: "lichess-m2-20",
    piece: "R",
    title: "Mate in 2 #20",
    instruction: "Find the two-move checkmate!",
    setup: "5k2/2pR1pp1/1bB1p1n1/1P2P1P1/2r2BK1/8/8/8 w - - 4 34",
    targets: [] as SquareId[],
    solution: ["d8", "e8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    mode: "checkmate",
    opponentResponses: [{ from: "f8" as SquareId, to: "e7" as SquareId }],
  },
];
