import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessPinPuzzles: Puzzle[] = [
  {
    id: "lichess-pin-01",
    piece: "R",
    title: "Pin #1",
    instruction: "Pin a piece so it can't move!",
    setup: "6K1/5R2/P7/6q1/8/6k1/8/8 w - - 5 70",
    targets: ["g7", "g5"] as SquareId[],
    solution: ["g7", "g5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g3" as SquareId, to: "h4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-02",
    piece: "R",
    title: "Pin #2",
    instruction: "Pin a piece so it can't move!",
    setup: "1K6/P1R5/8/1q6/1k6/8/8/8 w - - 7 64",
    targets: ["b7", "b5"] as SquareId[],
    solution: ["b7", "b5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "b4" as SquareId, to: "c5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-03",
    piece: "R",
    title: "Pin #3",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/8/8/7P/3R4/1kq1K3/8 w - - 1 65",
    targets: ["d2", "c2"] as SquareId[],
    solution: ["d2", "c2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "b2" as SquareId, to: "c3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-04",
    piece: "R",
    title: "Pin #4",
    instruction: "Pin a piece so it can't move!",
    setup: "4K3/4R3/4P3/5q2/5k2/8/8/8 w - - 3 78",
    targets: ["f7", "f5"] as SquareId[],
    solution: ["f7", "f5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f4" as SquareId, to: "g5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-05",
    piece: "R",
    title: "Pin #5",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/8/1kq5/6KR/5P2/8/8 w - - 7 65",
    targets: ["h5", "c5"] as SquareId[],
    solution: ["h5", "c5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "b5" as SquareId, to: "b4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-06",
    piece: "R",
    title: "Pin #6",
    instruction: "Pin a piece so it can't move!",
    setup: "2R5/4K3/8/2q5/2n5/8/8/2k5 w - - 10 60",
    targets: ["c5", "c4"] as SquareId[],
    solution: ["c5", "c4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c1" as SquareId, to: "d2" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-07",
    piece: "R",
    title: "Pin #7",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/4K3/6R1/8/2P5/4q3/4k3 w - - 1 66",
    targets: ["e5", "e2"] as SquareId[],
    solution: ["e5", "e2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e1" as SquareId, to: "d2" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-08",
    piece: "R",
    title: "Pin #8",
    instruction: "Pin a piece so it can't move!",
    setup: "8/6R1/5qPK/5k2/8/8/8/8 w - - 1 48",
    targets: ["f7", "f6"] as SquareId[],
    solution: ["f7", "f6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-09",
    piece: "R",
    title: "Pin #9",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/7R/5qPK/5k2/8/8/8 w - - 15 54",
    targets: ["f6", "f5"] as SquareId[],
    solution: ["f6", "f5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f4" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-10",
    piece: "B",
    title: "Pin #10",
    instruction: "Pin a piece so it can't move!",
    setup: "8/K1B5/8/P1q5/3k4/8/8/8 w - - 12 69",
    targets: ["b6", "c5"] as SquareId[],
    solution: ["b6", "c5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d4" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-11",
    piece: "R",
    title: "Pin #11",
    instruction: "Pin a piece so it can't move!",
    setup: "8/2K5/3RP3/8/8/2q5/2k5/8 w - - 4 67",
    targets: ["c6", "c3"] as SquareId[],
    solution: ["c6", "c3"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c2" as SquareId, to: "d3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-12",
    piece: "R",
    title: "Pin #12",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/2kq4/5RK1/8/5P2/8/8 w - - 1 71",
    targets: ["f6", "d6"] as SquareId[],
    solution: ["f6", "d6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c6" as SquareId, to: "c7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-13",
    piece: "R",
    title: "Pin #13",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/8/1KR5/3q1k2/1P6/8/8 w - - 2 70",
    targets: ["c4", "d4"] as SquareId[],
    solution: ["c4", "d4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f4" as SquareId, to: "e3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-14",
    piece: "R",
    title: "Pin #14",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/8/1R6/1KPq4/3k4/8/8 w - - 5 63",
    targets: ["d5", "d4"] as SquareId[],
    solution: ["d5", "d4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d3" as SquareId, to: "e3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-pin-15",
    piece: "R",
    title: "Pin #15",
    instruction: "Pin a piece so it can't move!",
    setup: "8/8/8/3kq1P1/6K1/5R2/8/8 w - - 6 65",
    targets: ["f5", "e5"] as SquareId[],
    solution: ["f5", "e5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
];
