import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessDiscoveredPuzzles: Puzzle[] = [
  {
    id: "lichess-disc-01",
    piece: "P",
    title: "Discovered Attack #1",
    instruction: "Move one piece to unleash another!",
    setup: "6k1/7p/p3P1p1/p1pBBp2/P1P3Pq/1rP4P/8/5K2 w - - 1 41",
    targets: [] as SquareId[],
    solution: ["e7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    strictSolution: true,
  },
  {
    id: "lichess-disc-02",
    piece: "B",
    title: "Discovered Attack #2",
    instruction: "Move one piece to unleash another!",
    setup: "2kr2nr/Bp4pp/5p2/4p3/2B5/P4n2/P4P1P/2R2K2 w - - 0 18",
    targets: [] as SquareId[],
    solution: ["b5"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    strictSolution: true,
  },
  {
    id: "lichess-disc-03",
    piece: "P",
    title: "Discovered Attack #3",
    instruction: "Move one piece to unleash another!",
    setup: "8/2r2bpk/p2q1p1p/1p6/3pPP2/1N1B3P/PP1Q2P1/6K1 w - - 1 41",
    targets: [] as SquareId[],
    solution: ["e5", "d6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "h7" as SquareId, to: "h8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-04",
    piece: "K",
    title: "Discovered Attack #4",
    instruction: "Move one piece to unleash another!",
    setup: "8/7p/6p1/n3k1P1/8/1pK1P3/1B5P/8 w - - 0 41",
    targets: [] as SquareId[],
    solution: ["b4", "a5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e5" as SquareId, to: "f5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-05",
    piece: "P",
    title: "Discovered Attack #5",
    instruction: "Move one piece to unleash another!",
    setup: "2r5/3bk3/1p1p4/p2p1pq1/P2P1pp1/2PBP1Pr/1P3K1P/R3RN2 w - - 0 32",
    targets: [] as SquareId[],
    solution: ["f4", "g5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e7" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-06",
    piece: "B",
    title: "Discovered Attack #6",
    instruction: "Move one piece to unleash another!",
    setup: "8/2n5/2P5/pB1k2pp/P2p4/1r4PP/5K2/2R5 w - - 0 45",
    targets: [] as SquareId[],
    solution: ["c4", "b3"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d5" as SquareId, to: "c6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-07",
    piece: "N",
    title: "Discovered Attack #7",
    instruction: "Move one piece to unleash another!",
    setup: "8/2q2Bkp/1n3np1/2p1p1N1/1p2b3/1Q5P/1PP2PP1/r2N1RK1 w - - 0 23",
    targets: [] as SquareId[],
    solution: ["e6", "c7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g7" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-08",
    piece: "N",
    title: "Discovered Attack #8",
    instruction: "Move one piece to unleash another!",
    setup: "2r3k1/3R2p1/1p5p/p1pN1p2/4b3/1PP1P2P/1P4P1/6K1 w - - 0 30",
    targets: [] as SquareId[],
    solution: ["e7", "c8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g8" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-09",
    piece: "P",
    title: "Discovered Attack #9",
    instruction: "Move one piece to unleash another!",
    setup: "r1b2r1k/pp4p1/1q3bp1/n4pPP/2QPp3/P1P5/2B2P2/R1B1K2R w KQ - 0 20",
    targets: [] as SquareId[],
    solution: ["g6"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    strictSolution: true,
  },
  {
    id: "lichess-disc-10",
    piece: "P",
    title: "Discovered Attack #10",
    instruction: "Move one piece to unleash another!",
    setup: "5rk1/pp5p/4PppQ/2p1qn2/2Br4/8/P1PN1PPP/5RK1 w - - 4 19",
    targets: [] as SquareId[],
    solution: ["e7", "f8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d4" as SquareId, to: "c4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-11",
    piece: "K",
    title: "Discovered Attack #11",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/R1K1k1p1/8/1r6/8/8/8 w - - 0 59",
    targets: [] as SquareId[],
    solution: ["c5", "b4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e6" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-12",
    piece: "B",
    title: "Discovered Attack #12",
    instruction: "Move one piece to unleash another!",
    setup: "r4k2/pR3Pp1/2p5/2np4/3b3B/8/P1P2P1P/6K1 w - - 1 26",
    targets: [] as SquareId[],
    solution: ["e7", "c5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f8" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-13",
    piece: "P",
    title: "Discovered Attack #13",
    instruction: "Move one piece to unleash another!",
    setup: "r4rk1/ppp3pp/1bnq1p2/1B2p3/2P5/1QP2N2/PP3PPP/R4nK1 w - - 0 15",
    targets: [] as SquareId[],
    solution: ["c5", "d6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-14",
    piece: "K",
    title: "Discovered Attack #14",
    instruction: "Move one piece to unleash another!",
    setup: "2r2rk1/1p1b1p2/1q2pB2/3pP2p/3P4/p1PB4/PP3nKP/R5R1 w - - 0 24",
    targets: [] as SquareId[],
    solution: ["f2"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    strictSolution: true,
  },
  {
    id: "lichess-disc-15",
    piece: "N",
    title: "Discovered Attack #15",
    instruction: "Move one piece to unleash another!",
    setup: "2r2k2/1pr1q2p/p3pp2/6p1/P1BP1N2/1P4P1/5PP1/R2R1K2 w - - 0 33",
    targets: [] as SquareId[],
    solution: ["e6", "c7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f8" as SquareId, to: "g8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-16",
    piece: "R",
    title: "Discovered Attack #16",
    instruction: "Move one piece to unleash another!",
    setup: "8/8/8/8/4k2p/5R2/6BK/4q3 w - - 8 61",
    targets: [] as SquareId[],
    solution: ["f1", "e1"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e4" as SquareId, to: "d4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-17",
    piece: "P",
    title: "Discovered Attack #17",
    instruction: "Move one piece to unleash another!",
    setup: "r1bq1r2/1pp3bk/3p3p/3PpP2/p1P5/P2B1N1P/1PQB4/2KR3n w - - 0 21",
    targets: [] as SquareId[],
    solution: ["f6", "g7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "h7" as SquareId, to: "h8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-18",
    piece: "R",
    title: "Discovered Attack #18",
    instruction: "Move one piece to unleash another!",
    setup: "6r1/p7/1p2p2k/3pP1r1/2nP4/1N4R1/PP6/6RK w - - 0 35",
    targets: [] as SquareId[],
    solution: ["h3", "g5", "g3", "g8"] as SquareId[],
    starThresholds: { three: 4, two: 5, one: 6 },
    opponentResponses: [{ from: "h6" as SquareId, to: "g6" as SquareId }, { from: "g6" as SquareId, to: "g5" as SquareId }, { from: "g5" as SquareId, to: "f5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-19",
    piece: "P",
    title: "Discovered Attack #19",
    instruction: "Move one piece to unleash another!",
    setup: "r2qr3/ppp2kbp/2n1b1p1/3P4/2Q2p2/B1P2P2/P1P3PP/R3R1K1 w - - 0 18",
    targets: [] as SquareId[],
    solution: ["e6", "e7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f7" as SquareId, to: "g8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-disc-20",
    piece: "R",
    title: "Discovered Attack #20",
    instruction: "Move one piece to unleash another!",
    setup: "4r3/8/1p4pk/1P5p/P1n5/2p3R1/2B1p1PP/6K1 w - - 0 42",
    targets: [] as SquareId[],
    solution: ["g6", "e6", "e8"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "h6" as SquareId, to: "h7" as SquareId }, { from: "h7" as SquareId, to: "g7" as SquareId }],
    strictSolution: true,
  },
];
