import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessForkPuzzles: Puzzle[] = [
  {
    id: "lichess-fork-01",
    piece: "N",
    title: "Fork #1",
    instruction: "Attack two pieces at once!",
    setup: "2NK4/8/2q5/3k4/8/8/8/8 w - - 14 70",
    targets: ["e7", "c6"] as SquareId[],
    solution: ["e7", "c6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "c5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-02",
    piece: "N",
    title: "Fork #2",
    instruction: "Attack two pieces at once!",
    setup: "8/8/8/8/5q2/2k3N1/6K1/8 w - - 12 67",
    targets: ["e2", "f4"] as SquareId[],
    solution: ["e2", "f4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c3" as SquareId, to: "c2" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-03",
    piece: "N",
    title: "Fork #3",
    instruction: "Attack two pieces at once!",
    setup: "8/8/1q6/2k5/8/2N5/2K5/8 w - - 3 68",
    targets: ["a4", "b6"] as SquareId[],
    solution: ["a4", "b6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c5" as SquareId, to: "c6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-04",
    piece: "N",
    title: "Fork #4",
    instruction: "Attack two pieces at once!",
    setup: "8/8/8/8/3K2k1/3P4/6N1/3r4 w - - 3 64",
    targets: ["e3", "d1"] as SquareId[],
    solution: ["e3", "d1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g4" as SquareId, to: "g5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-05",
    piece: "N",
    title: "Fork #5",
    instruction: "Attack two pieces at once!",
    setup: "8/8/q7/P7/1K6/1N1k4/8/8 w - - 1 59",
    targets: ["c5", "a6"] as SquareId[],
    solution: ["c5", "a6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d3" as SquareId, to: "d4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-06",
    piece: "N",
    title: "Fork #6",
    instruction: "Attack two pieces at once!",
    setup: "8/5k2/5P2/6K1/2r1N3/8/8/8 w - - 3 82",
    targets: ["d6", "c4"] as SquareId[],
    solution: ["d6", "c4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-07",
    piece: "N",
    title: "Fork #7",
    instruction: "Attack two pieces at once!",
    setup: "8/8/5K2/5P2/2k5/8/6N1/3q4 w - - 0 54",
    targets: ["e3", "d1"] as SquareId[],
    solution: ["e3", "d1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c4" as SquareId, to: "c5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-08",
    piece: "N",
    title: "Fork #8",
    instruction: "Attack two pieces at once!",
    setup: "6r1/8/8/6PN/4k2K/8/8/8 w - - 1 74",
    targets: ["f6", "g8"] as SquareId[],
    solution: ["f6", "g8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e4" as SquareId, to: "f5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-09",
    piece: "N",
    title: "Fork #9",
    instruction: "Attack two pieces at once!",
    setup: "8/5r2/8/5N2/4k1K1/8/6P1/8 w - - 1 62",
    targets: ["d6", "f7"] as SquareId[],
    solution: ["d6", "f7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e4" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-10",
    piece: "N",
    title: "Fork #10",
    instruction: "Attack two pieces at once!",
    setup: "4k1r1/6PN/6K1/8/8/8/8/8 w - - 9 67",
    targets: ["f6", "g8"] as SquareId[],
    solution: ["f6", "g8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e8" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-11",
    piece: "N",
    title: "Fork #11",
    instruction: "Attack two pieces at once!",
    setup: "6r1/7k/8/8/4N3/5KP1/8/8 w - - 2 53",
    targets: ["f6", "g8"] as SquareId[],
    solution: ["f6", "g8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h7" as SquareId, to: "g6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-12",
    piece: "N",
    title: "Fork #12",
    instruction: "Attack two pieces at once!",
    setup: "4r3/7k/8/3N4/3K4/4P3/8/8 w - - 7 54",
    targets: ["f6", "e8"] as SquareId[],
    solution: ["f6", "e8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h7" as SquareId, to: "g7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-13",
    piece: "R",
    title: "Fork #13",
    instruction: "Attack two pieces at once!",
    setup: "6q1/8/5K2/5R2/5P2/6k1/8/8 w - - 5 65",
    targets: ["g5", "g8"] as SquareId[],
    solution: ["g5", "g8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g3" as SquareId, to: "f4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-14",
    piece: "N",
    title: "Fork #14",
    instruction: "Attack two pieces at once!",
    setup: "8/8/8/5r2/6N1/7P/7K/5k2 w - - 5 48",
    targets: ["e3", "f5"] as SquareId[],
    solution: ["e3", "f5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f1" as SquareId, to: "e2" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-15",
    piece: "P",
    title: "Fork #15",
    instruction: "Attack two pieces at once!",
    setup: "8/8/5r1k/8/6PK/6P1/8/8 w - - 1 53",
    targets: ["g5", "f6"] as SquareId[],
    solution: ["g5", "f6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h6" as SquareId, to: "h7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-16",
    piece: "N",
    title: "Fork #16",
    instruction: "Attack two pieces at once!",
    setup: "8/5k2/2N5/8/1Pr5/8/7K/8 w - - 5 60",
    targets: ["e5", "c4"] as SquareId[],
    solution: ["e5", "c4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-17",
    piece: "P",
    title: "Fork #17",
    instruction: "Attack two pieces at once!",
    setup: "8/8/1k1r4/8/1PP5/1K6/8/8 w - - 1 98",
    targets: ["c5", "d6"] as SquareId[],
    solution: ["c5", "d6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "b6" as SquareId, to: "c7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-18",
    piece: "N",
    title: "Fork #18",
    instruction: "Attack two pieces at once!",
    setup: "8/7K/5NP1/6k1/8/8/3q4/8 w - - 11 69",
    targets: ["e4", "d2"] as SquareId[],
    solution: ["e4", "d2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g5" as SquareId, to: "f4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-19",
    piece: "N",
    title: "Fork #19",
    instruction: "Attack two pieces at once!",
    setup: "8/q7/8/PK6/1N1k4/8/8/8 w - - 1 58",
    targets: ["c6", "a7"] as SquareId[],
    solution: ["c6", "a7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d4" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-20",
    piece: "N",
    title: "Fork #20",
    instruction: "Attack two pieces at once!",
    setup: "8/8/3k3r/4N3/3K4/2P5/8/8 w - - 6 50",
    targets: ["f7", "h6"] as SquareId[],
    solution: ["f7", "h6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d6" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
];
