import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessSkewerPuzzles: Puzzle[] = [
  {
    id: "lichess-skewer-01",
    piece: "R",
    title: "Skewer #1",
    instruction: "Attack through one piece to win another!",
    setup: "3r4/8/8/8/3k4/8/2K1R3/8 w - - 10 80",
    targets: ["d2", "d8"] as SquareId[],
    solution: ["d2", "d8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d4" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-02",
    piece: "R",
    title: "Skewer #2",
    instruction: "Attack through one piece to win another!",
    setup: "8/2r2k2/7R/8/8/8/3K4/8 w - - 54 90",
    targets: ["h7", "c7"] as SquareId[],
    solution: ["h7", "c7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-03",
    piece: "R",
    title: "Skewer #3",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/1r2k3/7R/6K1/8/8/8 w - - 22 102",
    targets: ["h6", "b6"] as SquareId[],
    solution: ["h6", "b6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e6" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-04",
    piece: "R",
    title: "Skewer #4",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/r2k4/5RK1/8/8/8/8 w - - 10 74",
    targets: ["f6", "a6"] as SquareId[],
    solution: ["f6", "a6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d6" as SquareId, to: "c5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-05",
    piece: "R",
    title: "Skewer #5",
    instruction: "Attack through one piece to win another!",
    setup: "2r2k2/7R/8/8/1K6/8/8/8 w - - 11 66",
    targets: ["h8", "c8"] as SquareId[],
    solution: ["h8", "c8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f8" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-06",
    piece: "R",
    title: "Skewer #6",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/8/8/8/1r2k1K1/5R2 w - - 1 69",
    targets: ["f2", "b2"] as SquareId[],
    solution: ["f2", "b2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e2" as SquareId, to: "e3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-07",
    piece: "R",
    title: "Skewer #7",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/r2k4/5R2/8/5K2/8 w - - 7 54",
    targets: ["f5", "a5"] as SquareId[],
    solution: ["f5", "a5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-08",
    piece: "R",
    title: "Skewer #8",
    instruction: "Attack through one piece to win another!",
    setup: "5r2/8/8/5k2/8/8/4R3/6K1 w - - 42 80",
    targets: ["f2", "f8"] as SquareId[],
    solution: ["f2", "f8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-09",
    piece: "R",
    title: "Skewer #9",
    instruction: "Attack through one piece to win another!",
    setup: "8/2r2k2/7R/8/8/3K4/8/8 w - - 70 96",
    targets: ["h7", "c7"] as SquareId[],
    solution: ["h7", "c7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-10",
    piece: "R",
    title: "Skewer #10",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/8/8/2k2r2/KR6/8 w - - 64 95",
    targets: ["b3", "f3"] as SquareId[],
    solution: ["b3", "f3"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c3" as SquareId, to: "d4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-11",
    piece: "R",
    title: "Skewer #11",
    instruction: "Attack through one piece to win another!",
    setup: "4K1R1/8/8/5k2/8/8/8/5r2 w - - 44 113",
    targets: ["f8", "f1"] as SquareId[],
    solution: ["f8", "f1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-12",
    piece: "R",
    title: "Skewer #12",
    instruction: "Attack through one piece to win another!",
    setup: "8/r3k3/7R/8/8/4K3/8/8 w - - 11 59",
    targets: ["h7", "a7"] as SquareId[],
    solution: ["h7", "a7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e7" as SquareId, to: "d6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-13",
    piece: "R",
    title: "Skewer #13",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/6KR/r2k4/8/8/8 w - - 1 49",
    targets: ["h4", "a4"] as SquareId[],
    solution: ["h4", "a4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d4" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-14",
    piece: "R",
    title: "Skewer #14",
    instruction: "Attack through one piece to win another!",
    setup: "4K3/4R3/5k2/8/8/8/5r2/8 w - - 4 74",
    targets: ["f7", "f2"] as SquareId[],
    solution: ["f7", "f2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f6" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-15",
    piece: "R",
    title: "Skewer #15",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/8/8/7R/2r2k2/7K w - - 3 51",
    targets: ["h2", "c2"] as SquareId[],
    solution: ["h2", "c2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f2" as SquareId, to: "f3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-16",
    piece: "R",
    title: "Skewer #16",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/r2k1K2/4R3/8/8/8/8 w - - 33 88",
    targets: ["e6", "a6"] as SquareId[],
    solution: ["e6", "a6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d6" as SquareId, to: "c5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-17",
    piece: "R",
    title: "Skewer #17",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/4RK2/r2k4/8/8/8/8 w - - 42 100",
    targets: ["e5", "a5"] as SquareId[],
    solution: ["e5", "a5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "d4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-18",
    piece: "R",
    title: "Skewer #18",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/8/6R1/r3k2K/8/8 w - - 9 74",
    targets: ["g3", "a3"] as SquareId[],
    solution: ["g3", "a3"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e3" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-19",
    piece: "R",
    title: "Skewer #19",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/3k3r/R7/5K2/8/8 w - - 11 66",
    targets: ["a5", "h5"] as SquareId[],
    solution: ["a5", "h5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "c6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-20",
    piece: "R",
    title: "Skewer #20",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/8/8/K1k3r1/1R6/8 w - - 1 70",
    targets: ["b3", "g3"] as SquareId[],
    solution: ["b3", "g3"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c3" as SquareId, to: "d4" as SquareId }],
    strictSolution: true,
  },
];
