import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessMateIn2Puzzles: Puzzle[] = [
  {
    id: "lichess-m2-01",
    piece: "P",
    title: "Mate in 2 #1",
    instruction: "Find the two-move checkmate!",
    setup: "7k/8/5PK1/8/8/8/4p3/8 w - - 0 62",
    targets: [] as SquareId[],
    solution: ["f7", "f8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "e2" as SquareId, to: "e1" as SquareId }],
  },
  {
    id: "lichess-m2-02",
    piece: "R",
    title: "Mate in 2 #2",
    instruction: "Find the two-move checkmate!",
    setup: "6r1/8/8/8/8/2K4R/8/2k5 w - - 3 65",
    targets: [] as SquareId[],
    solution: ["h1", "g1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "g8" as SquareId, to: "g1" as SquareId }],
  },
  {
    id: "lichess-m2-03",
    piece: "R",
    title: "Mate in 2 #3",
    instruction: "Find the two-move checkmate!",
    setup: "1k6/4r3/1K6/8/6R1/8/8/8 w - - 12 64",
    targets: [] as SquareId[],
    solution: ["g8", "e8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "e7" as SquareId, to: "e8" as SquareId }],
  },
  {
    id: "lichess-m2-04",
    piece: "R",
    title: "Mate in 2 #4",
    instruction: "Find the two-move checkmate!",
    setup: "k7/8/1K2R3/8/8/8/8/2r5 w - - 5 78",
    targets: [] as SquareId[],
    solution: ["e8", "c8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "c1" as SquareId, to: "c8" as SquareId }],
  },
  {
    id: "lichess-m2-05",
    piece: "R",
    title: "Mate in 2 #5",
    instruction: "Find the two-move checkmate!",
    setup: "4k3/1r6/R3K3/8/8/8/8/8 w - - 35 69",
    targets: [] as SquareId[],
    solution: ["a8", "b8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "b7" as SquareId, to: "b8" as SquareId }],
  },
  {
    id: "lichess-m2-06",
    piece: "R",
    title: "Mate in 2 #6",
    instruction: "Find the two-move checkmate!",
    setup: "2k5/4r3/2K3R1/8/8/8/8/8 w - - 2 49",
    targets: [] as SquareId[],
    solution: ["g8", "e8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "e7" as SquareId, to: "e8" as SquareId }],
  },
  {
    id: "lichess-m2-07",
    piece: "R",
    title: "Mate in 2 #7",
    instruction: "Find the two-move checkmate!",
    setup: "2k5/5r2/2K5/8/7R/8/8/8 w - - 9 64",
    targets: [] as SquareId[],
    solution: ["h8", "f8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "f7" as SquareId, to: "f8" as SquareId }],
  },
  {
    id: "lichess-m2-08",
    piece: "R",
    title: "Mate in 2 #8",
    instruction: "Find the two-move checkmate!",
    setup: "7k/5K2/r7/5R2/8/8/8/8 w - - 35 74",
    targets: [] as SquareId[],
    solution: ["h5", "h6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "a6" as SquareId, to: "h6" as SquareId }],
  },
  {
    id: "lichess-m2-09",
    piece: "R",
    title: "Mate in 2 #9",
    instruction: "Find the two-move checkmate!",
    setup: "8/8/8/8/8/R4K2/1r6/5k2 w - - 50 78",
    targets: [] as SquareId[],
    solution: ["a1", "b1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "b2" as SquareId, to: "b1" as SquareId }],
  },
  {
    id: "lichess-m2-10",
    piece: "R",
    title: "Mate in 2 #10",
    instruction: "Find the two-move checkmate!",
    setup: "2k5/4r3/2K5/8/8/7R/8/8 w - - 11 67",
    targets: [] as SquareId[],
    solution: ["h8", "e8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "e7" as SquareId, to: "e8" as SquareId }],
  },
  {
    id: "lichess-m2-11",
    piece: "R",
    title: "Mate in 2 #11",
    instruction: "Find the two-move checkmate!",
    setup: "5k2/8/5K2/8/1r6/8/R7/8 w - - 2 61",
    targets: [] as SquareId[],
    solution: ["a8", "b8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "b4" as SquareId, to: "b8" as SquareId }],
  },
  {
    id: "lichess-m2-12",
    piece: "R",
    title: "Mate in 2 #12",
    instruction: "Find the two-move checkmate!",
    setup: "2R5/1r6/8/8/8/k1K5/8/8 w - - 10 74",
    targets: [] as SquareId[],
    solution: ["a8", "a7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "b7" as SquareId, to: "a7" as SquareId }],
  },
  {
    id: "lichess-m2-13",
    piece: "R",
    title: "Mate in 2 #13",
    instruction: "Find the two-move checkmate!",
    setup: "2R5/3r4/8/8/8/8/2K5/k7 w - - 1 72",
    targets: [] as SquareId[],
    solution: ["a8", "a7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "d7" as SquareId, to: "a7" as SquareId }],
  },
  {
    id: "lichess-m2-14",
    piece: "R",
    title: "Mate in 2 #14",
    instruction: "Find the two-move checkmate!",
    setup: "6k1/3r4/6K1/8/8/8/1R6/8 w - - 1 70",
    targets: [] as SquareId[],
    solution: ["b8", "d8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "d7" as SquareId, to: "d8" as SquareId }],
  },
  {
    id: "lichess-m2-15",
    piece: "R",
    title: "Mate in 2 #15",
    instruction: "Find the two-move checkmate!",
    setup: "2R5/1r6/8/k1K5/8/8/8/8 w - - 8 68",
    targets: [] as SquareId[],
    solution: ["a8", "a7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "b7" as SquareId, to: "a7" as SquareId }],
  },
  {
    id: "lichess-m2-16",
    piece: "R",
    title: "Mate in 2 #16",
    instruction: "Find the two-move checkmate!",
    setup: "8/8/8/5K1k/8/8/r7/5R2 w - - 17 82",
    targets: [] as SquareId[],
    solution: ["h1", "h2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "a2" as SquareId, to: "h2" as SquareId }],
  },
  {
    id: "lichess-m2-17",
    piece: "R",
    title: "Mate in 2 #17",
    instruction: "Find the two-move checkmate!",
    setup: "8/8/8/8/5K1k/8/6r1/R7 w - - 10 73",
    targets: [] as SquareId[],
    solution: ["h1", "h2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "g2" as SquareId, to: "h2" as SquareId }],
  },
  {
    id: "lichess-m2-18",
    piece: "R",
    title: "Mate in 2 #18",
    instruction: "Find the two-move checkmate!",
    setup: "8/8/8/8/5r2/3K3R/8/3k4 w - - 59 85",
    targets: [] as SquareId[],
    solution: ["h1", "f1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "f4" as SquareId, to: "f1" as SquareId }],
  },
  {
    id: "lichess-m2-19",
    piece: "R",
    title: "Mate in 2 #19",
    instruction: "Find the two-move checkmate!",
    setup: "2R5/1r6/8/8/8/8/k1K5/8 w - - 46 89",
    targets: [] as SquareId[],
    solution: ["a8", "a7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "b7" as SquareId, to: "a7" as SquareId }],
  },
  {
    id: "lichess-m2-20",
    piece: "R",
    title: "Mate in 2 #20",
    instruction: "Find the two-move checkmate!",
    setup: "5k2/2r5/R4K2/8/8/8/8/8 w - - 7 59",
    targets: [] as SquareId[],
    solution: ["a8", "c8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    mode: "checkmate",
    opponentResponses: [{ from: "c7" as SquareId, to: "c8" as SquareId }],
  },
];
