import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessMateIn1Puzzles: Puzzle[] = [
  {
    id: "lichess-m1-01",
    piece: "Q",
    title: "Mate in 1 #1",
    instruction: "Find the checkmate!",
    setup: "6k1/1pq2ppp/p3p3/3p4/QPrPnP2/P5P1/4NP1P/R5K1 w - - 1 23",
    targets: [] as SquareId[],
    solution: ["e8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-02",
    piece: "Q",
    title: "Mate in 1 #2",
    instruction: "Find the checkmate!",
    setup: "rn2r1k1/pp3ppp/2p3b1/3p4/3P1PPq/2B1Q2P/PPP1Bn2/2KR3R w - - 1 16",
    targets: [] as SquareId[],
    solution: ["e8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-03",
    piece: "R",
    title: "Mate in 1 #3",
    instruction: "Find the checkmate!",
    setup: "5R2/8/5Kpk/5p1p/6rP/8/8/8 w - - 2 66",
    targets: [] as SquareId[],
    solution: ["h8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-04",
    piece: "Q",
    title: "Mate in 1 #4",
    instruction: "Find the checkmate!",
    setup: "r3kbnr/p1pb1ppp/2p2q2/4N3/3Q4/8/PPP2PPP/RNB1K2R w KQkq - 1 9",
    targets: [] as SquareId[],
    solution: ["d7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-05",
    piece: "R",
    title: "Mate in 1 #5",
    instruction: "Find the checkmate!",
    setup: "k4br1/p1R5/1ppN1p2/4p3/2P5/4BP2/b7/2K5 w - - 5 31",
    targets: [] as SquareId[],
    solution: ["c8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-06",
    piece: "Q",
    title: "Mate in 1 #6",
    instruction: "Find the checkmate!",
    setup: "4k2r/1pr1ppbp/5np1/8/q7/3QB3/PPP2PPP/1R1R2K1 w k - 0 18",
    targets: [] as SquareId[],
    solution: ["d8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-07",
    piece: "R",
    title: "Mate in 1 #7",
    instruction: "Find the checkmate!",
    setup: "R2r2k1/6pp/3N4/1nP5/6P1/1P3P2/P2K2n1/8 w - - 2 31",
    targets: [] as SquareId[],
    solution: ["d8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-08",
    piece: "Q",
    title: "Mate in 1 #8",
    instruction: "Find the checkmate!",
    setup: "3rk1nr/p1p2ppp/1p6/8/2Q1P3/4PRP1/P1P3BP/qN5K w k - 0 18",
    targets: [] as SquareId[],
    solution: ["f7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-09",
    piece: "Q",
    title: "Mate in 1 #9",
    instruction: "Find the checkmate!",
    setup: "r2q1rk1/p1nn2p1/1pp1p2p/3pPp1N/3P1b2/P1N3Q1/1PP2PP1/R3R1K1 w - - 0 18",
    targets: [] as SquareId[],
    solution: ["g7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-10",
    piece: "Q",
    title: "Mate in 1 #10",
    instruction: "Find the checkmate!",
    setup: "7k/7n/2p2r2/p1P3q1/P2pB3/3P2PQ/4PPK1/1r6 w - - 0 42",
    targets: [] as SquareId[],
    solution: ["h7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-11",
    piece: "R",
    title: "Mate in 1 #11",
    instruction: "Find the checkmate!",
    setup: "r1b3k1/p4p1p/2p3p1/3n4/8/3q2BP/P4PP1/Q3R1K1 w - - 2 20",
    targets: [] as SquareId[],
    solution: ["e8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-12",
    piece: "Q",
    title: "Mate in 1 #12",
    instruction: "Find the checkmate!",
    setup: "rn1q1b1r/5kp1/p2pb2p/8/3Nn3/1Q6/PP3PPP/R1B1K2R w KQ - 0 13",
    targets: [] as SquareId[],
    solution: ["e6"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-13",
    piece: "Q",
    title: "Mate in 1 #13",
    instruction: "Find the checkmate!",
    setup: "r1bq1r1k/p1p2ppp/1pnp4/8/2P1P3/2Q2P2/PP1N1P1P/2KR1BR1 w - - 2 13",
    targets: [] as SquareId[],
    solution: ["g7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-14",
    piece: "Q",
    title: "Mate in 1 #14",
    instruction: "Find the checkmate!",
    setup: "7R/p4p2/1p2p1p1/5k1p/3Q4/8/PP3KNr/7q w - - 18 37",
    targets: [] as SquareId[],
    solution: ["f4"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-15",
    piece: "Q",
    title: "Mate in 1 #15",
    instruction: "Find the checkmate!",
    setup: "3r1r1k/ppp2pnp/3b3Q/7q/2B1N1R1/P4P2/1P5P/2K5 w - - 3 23",
    targets: [] as SquareId[],
    solution: ["g7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-16",
    piece: "Q",
    title: "Mate in 1 #16",
    instruction: "Find the checkmate!",
    setup: "5r1k/p1p4p/2pq1r2/3p3P/3Pb1Q1/2P5/P1P5/R3KBR1 w Q - 1 19",
    targets: [] as SquareId[],
    solution: ["g7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-17",
    piece: "R",
    title: "Mate in 1 #17",
    instruction: "Find the checkmate!",
    setup: "5n1k/8/p2p2Q1/3r4/2p4q/1P4p1/P5PP/5R1K w - - 0 35",
    targets: [] as SquareId[],
    solution: ["f8"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-18",
    piece: "Q",
    title: "Mate in 1 #18",
    instruction: "Find the checkmate!",
    setup: "r3k2r/p4ppp/n1P2qn1/4p3/2p1P1Q1/B1P4P/P4PP1/1R2K2R w Kkq - 0 15",
    targets: [] as SquareId[],
    solution: ["d7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-19",
    piece: "P",
    title: "Mate in 1 #19",
    instruction: "Find the checkmate!",
    setup: "r6k/pp2Nnrp/5Pp1/8/3B4/8/P1qp2bP/R4RK1 w - - 0 27",
    targets: [] as SquareId[],
    solution: ["g7"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
  {
    id: "lichess-m1-20",
    piece: "N",
    title: "Mate in 1 #20",
    instruction: "Find the checkmate!",
    setup: "2r2k2/1b3Pp1/p5qp/3B4/5N1P/1Pp3P1/P6K/5R2 w - - 0 35",
    targets: [] as SquareId[],
    solution: ["g6"] as SquareId[],
    starThresholds: { three: 1, two: 2, one: 3 },
    mode: "checkmate",
  },
];
