import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessSkewerPuzzles: Puzzle[] = [
  {
    id: "lichess-skewer-01",
    piece: "R",
    title: "Skewer #1",
    instruction: "Attack through one piece to win another!",
    setup: "3R4/5p1p/4k1p1/1K1p4/5P1P/4r1P1/8/8 w - - 0 53",
    targets: [] as SquareId[],
    solution: ["e8", "e3"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e6" as SquareId, to: "f5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-02",
    piece: "R",
    title: "Skewer #2",
    instruction: "Attack through one piece to win another!",
    setup: "8/p7/8/6p1/1P6/PK6/4k2r/R7 w - - 0 49",
    targets: [] as SquareId[],
    solution: ["a2", "h2"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e2" as SquareId, to: "e3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-03",
    piece: "R",
    title: "Skewer #3",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/K4p2/P7/1r3k2/8/7R/8 w - - 0 50",
    targets: [] as SquareId[],
    solution: ["h4", "b4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f4" as SquareId, to: "e3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-04",
    piece: "R",
    title: "Skewer #4",
    instruction: "Attack through one piece to win another!",
    setup: "R7/8/5pk1/7p/8/2P2K2/1P6/6r1 w - - 7 52",
    targets: [] as SquareId[],
    solution: ["g8", "g1"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g6" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-05",
    piece: "R",
    title: "Skewer #5",
    instruction: "Attack through one piece to win another!",
    setup: "r4k2/pp2b2R/8/2p1pp2/8/P1P2K2/1P3P2/8 w - - 0 32",
    targets: [] as SquareId[],
    solution: ["h8", "a8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f8" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-06",
    piece: "R",
    title: "Skewer #6",
    instruction: "Attack through one piece to win another!",
    setup: "8/6R1/1p4pp/2p2k2/8/2K4P/5rP1/8 w - - 1 54",
    targets: [] as SquareId[],
    solution: ["f7", "f2"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f5" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-07",
    piece: "R",
    title: "Skewer #7",
    instruction: "Attack through one piece to win another!",
    setup: "R7/8/4kpp1/8/7p/4r2P/6PK/8 w - - 0 64",
    targets: [] as SquareId[],
    solution: ["e8", "e3"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e6" as SquareId, to: "d7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-08",
    piece: "R",
    title: "Skewer #8",
    instruction: "Attack through one piece to win another!",
    setup: "8/1p6/6p1/3p3p/1P5P/3R4/2K1k2r/8 w - - 0 54",
    targets: [] as SquareId[],
    solution: ["d2", "h2"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e2" as SquareId, to: "f3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-09",
    piece: "R",
    title: "Skewer #9",
    instruction: "Attack through one piece to win another!",
    setup: "rn2k2r/8/4pp2/p2p1n1p/Pb1P3P/2R1B3/3N1PP1/4KB1R w Kkq - 0 22",
    targets: [] as SquareId[],
    solution: ["c8", "h8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e8" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-10",
    piece: "R",
    title: "Skewer #10",
    instruction: "Attack through one piece to win another!",
    setup: "8/2kb3p/2p1p1p1/R4p2/2NP1P2/3r4/5KPP/8 w - - 23 50",
    targets: [] as SquareId[],
    solution: ["a7", "d7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "c7" as SquareId, to: "b8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-11",
    piece: "R",
    title: "Skewer #11",
    instruction: "Attack through one piece to win another!",
    setup: "5r2/3qkp2/p5p1/4p3/p1BpP3/1P6/2P2R2/1K3R2 w - - 2 44",
    targets: [] as SquareId[],
    solution: ["f7", "f7", "d7"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "f8" as SquareId, to: "f7" as SquareId }, { from: "e7" as SquareId, to: "e8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-12",
    piece: "R",
    title: "Skewer #12",
    instruction: "Attack through one piece to win another!",
    setup: "8/2R2R2/8/3p2Pp/r2k4/7r/5P2/6K1 w - - 0 37",
    targets: [] as SquareId[],
    solution: ["f4", "a4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d4" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-13",
    piece: "R",
    title: "Skewer #13",
    instruction: "Attack through one piece to win another!",
    setup: "3R4/8/8/p1kp4/P3n1P1/1P6/2r2PK1/8 w - - 1 49",
    targets: [] as SquareId[],
    solution: ["c8", "c2"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "c5" as SquareId, to: "b4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-14",
    piece: "R",
    title: "Skewer #14",
    instruction: "Attack through one piece to win another!",
    setup: "1R1b4/5p2/1p1r2k1/1p4P1/1Ppn1P2/7R/8/1K6 w - - 1 38",
    targets: [] as SquareId[],
    solution: ["h6", "d6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g6" as SquareId, to: "g7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-15",
    piece: "R",
    title: "Skewer #15",
    instruction: "Attack through one piece to win another!",
    setup: "8/8/8/5R2/8/6K1/1r2k3/8 w - - 3 56",
    targets: [] as SquareId[],
    solution: ["f2", "b2"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e2" as SquareId, to: "d3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-16",
    piece: "Q",
    title: "Skewer #16",
    instruction: "Attack through one piece to win another!",
    setup: "4r3/p2q4/4kp2/1p1p4/1Bpr1PpQ/P7/KPP5/8 w - - 0 39",
    targets: [] as SquareId[],
    solution: ["g4", "d7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e6" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-17",
    piece: "R",
    title: "Skewer #17",
    instruction: "Attack through one piece to win another!",
    setup: "3b4/6BP/6K1/1ppk4/6p1/5p2/2R2P1r/8 w - - 2 45",
    targets: [] as SquareId[],
    solution: ["d2", "d8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-18",
    piece: "Q",
    title: "Skewer #18",
    instruction: "Attack through one piece to win another!",
    setup: "8/6K1/6P1/1p6/8/2kp4/7Q/q7 w - - 0 52",
    targets: [] as SquareId[],
    solution: ["e5", "a1"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "c3" as SquareId, to: "c2" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-19",
    piece: "R",
    title: "Skewer #19",
    instruction: "Attack through one piece to win another!",
    setup: "8/2R3p1/5krp/3Kp3/4P3/6P1/8/8 w - - 1 43",
    targets: [] as SquareId[],
    solution: ["c6", "g6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f6" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-skewer-20",
    piece: "R",
    title: "Skewer #20",
    instruction: "Attack through one piece to win another!",
    setup: "8/pppr1k2/2p5/4R3/5K2/2r2P2/P7/7R w - - 0 27",
    targets: [] as SquareId[],
    solution: ["h7", "d7", "e4"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "f7" as SquareId, to: "f6" as SquareId }, { from: "c3" as SquareId, to: "c4" as SquareId }],
    strictSolution: true,
  },
];
