import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessRemovingDefenderPuzzles: Puzzle[] = [
  {
    id: "lichess-rtd-01",
    piece: "R",
    title: "Remove the Defender #1",
    instruction: "Capture the piece that guards the target!",
    setup: "8/8/8/6R1/5r2/2P3p1/2KR4/5kr1 w - - 4 62",
    targets: ["d1", "g1", "g3"] as SquareId[],
    solution: ["d1", "g1", "g3"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f1" as SquareId, to: "f2" as SquareId }, { from: "f2" as SquareId, to: "g1" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-02",
    piece: "R",
    title: "Remove the Defender #2",
    instruction: "Capture the piece that guards the target!",
    setup: "8/8/3R4/8/8/KPk2r2/P1r1b2R/8 w - - 11 58",
    targets: ["c6", "c2", "e2"] as SquareId[],
    solution: ["c6", "c2", "e2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "c3" as SquareId, to: "d3" as SquareId }, { from: "d3" as SquareId, to: "c2" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-03",
    piece: "R",
    title: "Remove the Defender #3",
    instruction: "Capture the piece that guards the target!",
    setup: "8/6R1/5pn1/p2R4/5krp/2P5/1K6/8 w - - 0 48",
    targets: ["d4", "g4", "g6"] as SquareId[],
    solution: ["d4", "g4", "g6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f4" as SquareId, to: "f5" as SquareId }, { from: "f5" as SquareId, to: "g4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-04",
    piece: "R",
    title: "Remove the Defender #4",
    instruction: "Capture the piece that guards the target!",
    setup: "8/4R3/6p1/3k4/1n1rp2P/3b4/1R4P1/6K1 w - - 2 42",
    targets: ["d7", "d4", "b4"] as SquareId[],
    solution: ["d7", "d4", "b4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "c5" as SquareId }, { from: "c5" as SquareId, to: "d4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-05",
    piece: "R",
    title: "Remove the Defender #5",
    instruction: "Capture the piece that guards the target!",
    setup: "r7/8/P7/1P1k4/P1R1r2p/1K6/8/4b2R w - - 7 53",
    targets: ["e4", "e1"] as SquareId[],
    solution: ["e4", "e1"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-06",
    piece: "R",
    title: "Remove the Defender #6",
    instruction: "Capture the piece that guards the target!",
    setup: "3r2k1/p1R2r1p/6p1/8/8/1P3P1R/P3K3/8 w - - 1 34",
    targets: ["f7", "h7"] as SquareId[],
    solution: ["f7", "h7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g8" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-07",
    piece: "R",
    title: "Remove the Defender #7",
    instruction: "Capture the piece that guards the target!",
    setup: "r4k2/pR2r1n1/8/1P5p/P4P2/4P3/4K1R1/8 w - - 2 40",
    targets: ["e7", "g7"] as SquareId[],
    solution: ["e7", "g7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f8" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-08",
    piece: "R",
    title: "Remove the Defender #8",
    instruction: "Capture the piece that guards the target!",
    setup: "5rk1/1R3pp1/1b3r1p/8/1P5P/5RP1/5P2/6K1 w - - 1 37",
    targets: ["f6", "b6"] as SquareId[],
    solution: ["f6", "b6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "g7" as SquareId, to: "f6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-09",
    piece: "B",
    title: "Remove the Defender #9",
    instruction: "Capture the piece that guards the target!",
    setup: "5bk1/5p2/3p1P2/3P1P2/B2B2p1/6P1/1rp5/6K1 w - - 0 51",
    targets: ["b2", "c2"] as SquareId[],
    solution: ["b2", "c2"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f8" as SquareId, to: "h6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-10",
    piece: "R",
    title: "Remove the Defender #10",
    instruction: "Capture the piece that guards the target!",
    setup: "1r5k/6pp/pP6/1r2p3/8/6P1/5P1P/1R2R1K1 w - - 1 33",
    targets: ["b5", "e5", "b5"] as SquareId[],
    solution: ["b5", "e5", "b5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "a6" as SquareId, to: "b5" as SquareId }, { from: "h8" as SquareId, to: "g8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-11",
    piece: "R",
    title: "Remove the Defender #11",
    instruction: "Capture the piece that guards the target!",
    setup: "4b1k1/R3Pr2/5b1p/2p3p1/2P5/3R2KP/1P6/8 w - - 1 39",
    targets: ["d8", "e7", "e8"] as SquareId[],
    solution: ["d8", "e7", "e8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e7" as SquareId }, { from: "f6" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-12",
    piece: "R",
    title: "Remove the Defender #12",
    instruction: "Capture the piece that guards the target!",
    setup: "3R4/6p1/p3kp2/8/2p2p1P/P3rb2/1P6/2K2R2 w - - 2 34",
    targets: ["e8", "e3", "f3"] as SquareId[],
    solution: ["e8", "e3", "f3"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e6" as SquareId, to: "f5" as SquareId }, { from: "f4" as SquareId, to: "e3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-13",
    piece: "R",
    title: "Remove the Defender #13",
    instruction: "Capture the piece that guards the target!",
    setup: "8/p2r1k2/1p3r2/1P1p2p1/P2R1P2/5K1R/5P2/8 w - - 0 47",
    targets: ["h7", "d7", "d5"] as SquareId[],
    solution: ["h7", "d7", "d5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }, { from: "e6" as SquareId, to: "d7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-14",
    piece: "R",
    title: "Remove the Defender #14",
    instruction: "Capture the piece that guards the target!",
    setup: "2r3k1/1R3ppp/1p2r3/1P6/8/P6P/6P1/4R1K1 w - - 1 27",
    targets: ["e6", "b6"] as SquareId[],
    solution: ["e6", "b6"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-15",
    piece: "R",
    title: "Remove the Defender #15",
    instruction: "Capture the piece that guards the target!",
    setup: "5n1R/R7/p3kr2/1p1p2p1/6P1/1P4K1/P1n5/8 w - - 6 42",
    targets: ["a6", "f6", "f8"] as SquareId[],
    solution: ["a6", "f6", "f8"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e6" as SquareId, to: "e5" as SquareId }, { from: "e5" as SquareId, to: "f6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-16",
    piece: "B",
    title: "Remove the Defender #16",
    instruction: "Capture the piece that guards the target!",
    setup: "5b2/2p2n2/1pB1k1p1/1P2p3/4P3/2BKP3/6P1/8 w - - 5 40",
    targets: ["d5", "f7", "e5"] as SquareId[],
    solution: ["d5", "f7", "e5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e6" as SquareId, to: "f6" as SquareId }, { from: "f6" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-17",
    piece: "R",
    title: "Remove the Defender #17",
    instruction: "Capture the piece that guards the target!",
    setup: "5r1k/2bR1Ppp/8/8/B7/7P/P3n1P1/2r1R2K w - - 5 30",
    targets: ["c1", "c7"] as SquareId[],
    solution: ["c1", "c7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "e2" as SquareId, to: "c1" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-18",
    piece: "R",
    title: "Remove the Defender #18",
    instruction: "Capture the piece that guards the target!",
    setup: "6k1/5p1p/1p2p1p1/3p4/1br2P2/6P1/7P/1RR4K w - - 0 34",
    targets: ["c4", "b4"] as SquareId[],
    solution: ["c4", "b4"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "d5" as SquareId, to: "c4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-19",
    piece: "R",
    title: "Remove the Defender #19",
    instruction: "Capture the piece that guards the target!",
    setup: "7k/pb2n1r1/2r5/2p3RP/P7/1P4P1/5P2/4R1K1 w - - 3 44",
    targets: ["g7", "e7", "b7"] as SquareId[],
    solution: ["g7", "e7", "b7"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "h8" as SquareId, to: "g7" as SquareId }, { from: "g7" as SquareId, to: "h6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-20",
    piece: "B",
    title: "Remove the Defender #20",
    instruction: "Capture the piece that guards the target!",
    setup: "R7/5pkp/6p1/4n3/1P2r3/3B1b2/1B1b3P/5K2 w - - 0 42",
    targets: ["e4", "e5"] as SquareId[],
    solution: ["e4", "e5"] as SquareId[],
    starThresholds: { three: 0, two: 1, one: 2 },
    opponentResponses: [{ from: "f3" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
];
