import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessForkPuzzles: Puzzle[] = [
  {
    id: "lichess-fork-01",
    piece: "R",
    title: "Fork #1",
    instruction: "Attack two pieces at once!",
    setup: "8/n4k2/6pp/4Kp2/2b5/p5P1/3R3P/8 w - - 2 49",
    targets: [] as SquareId[],
    solution: ["d7", "a7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-02",
    piece: "N",
    title: "Fork #2",
    instruction: "Attack two pieces at once!",
    setup: "2r3k1/5p1p/p1Nr1p2/1p1P4/1P2b3/1B6/5PPP/3R2K1 w - - 6 28",
    targets: [] as SquareId[],
    solution: ["e7", "c8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g8" as SquareId, to: "f8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-03",
    piece: "Q",
    title: "Fork #3",
    instruction: "Attack two pieces at once!",
    setup: "r4rk1/pp4p1/6p1/3pb3/2p4q/P1P1BP1P/1P3P2/R2Q1RK1 w - - 1 19",
    targets: [] as SquareId[],
    solution: ["d5", "e5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g8" as SquareId, to: "h7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-04",
    piece: "N",
    title: "Fork #4",
    instruction: "Attack two pieces at once!",
    setup: "8/4kp2/3np3/rpnp2p1/3N2P1/1BP2P2/P1K5/1R6 w - - 2 42",
    targets: [] as SquareId[],
    solution: ["c6", "a5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e7" as SquareId, to: "d7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-05",
    piece: "Q",
    title: "Fork #5",
    instruction: "Attack two pieces at once!",
    setup: "r1bk4/ppppb1r1/2n5/6BQ/4p3/3P4/PPP2P1P/RN2K1Nq w Q - 2 14",
    targets: [] as SquareId[],
    solution: ["h8", "g8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g7" as SquareId, to: "g8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-06",
    piece: "N",
    title: "Fork #6",
    instruction: "Attack two pieces at once!",
    setup: "8/p7/1p6/4kp2/1P3N1r/P4K2/1P5P/8 w - - 6 39",
    targets: [] as SquareId[],
    solution: ["g6", "h4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e5" as SquareId, to: "d5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-07",
    piece: "Q",
    title: "Fork #7",
    instruction: "Attack two pieces at once!",
    setup: "r1b1n1k1/1pQ3pp/p7/P2p2q1/8/8/1P4PP/5R1K w - - 0 26",
    targets: [] as SquareId[],
    solution: ["f7", "e8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-08",
    piece: "P",
    title: "Fork #8",
    instruction: "Attack two pieces at once!",
    setup: "8/5p2/4p2R/3pk1r1/8/2P1KP2/8/8 w - - 7 50",
    targets: [] as SquareId[],
    solution: ["f4", "g5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e5" as SquareId, to: "f5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-09",
    piece: "P",
    title: "Fork #9",
    instruction: "Attack two pieces at once!",
    setup: "8/5p2/4r1k1/p1P5/5PP1/r3B2P/4K3/2R5 w - - 1 36",
    targets: [] as SquareId[],
    solution: ["f5", "e6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g6" as SquareId, to: "f6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-10",
    piece: "N",
    title: "Fork #10",
    instruction: "Attack two pieces at once!",
    setup: "8/p1r5/1p1N1k1p/4p2p/P1Bp1p2/1P3P2/3R2PK/r7 w - - 2 45",
    targets: [] as SquareId[],
    solution: ["e8", "c7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f6" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-11",
    piece: "N",
    title: "Fork #11",
    instruction: "Attack two pieces at once!",
    setup: "r3kb1r/3n1ppp/pp1p1P2/3N4/P1P2p2/8/2P2PPP/R4RK1 w kq - 0 16",
    targets: [] as SquareId[],
    solution: ["c7", "a8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "e8" as SquareId, to: "d8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-12",
    piece: "N",
    title: "Fork #12",
    instruction: "Attack two pieces at once!",
    setup: "2r5/1k1p2p1/1p2p3/1q2P3/4NPPr/4Q2P/1P6/1K6 w - - 0 36",
    targets: [] as SquareId[],
    solution: ["d6", "b5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "b7" as SquareId, to: "a6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-13",
    piece: "N",
    title: "Fork #13",
    instruction: "Attack two pieces at once!",
    setup: "8/pp6/2p3Q1/3p4/2k3KP/P1P3b1/8/1N3q2 w - - 0 46",
    targets: [] as SquareId[],
    solution: ["d2", "f1"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "c4" as SquareId, to: "c3" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-14",
    piece: "B",
    title: "Fork #14",
    instruction: "Attack two pieces at once!",
    setup: "8/3k4/ppnB2B1/5p1P/1P3P2/P6r/1K6/8 w - - 0 42",
    targets: [] as SquareId[],
    solution: ["f5", "h3"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d7" as SquareId, to: "d6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-15",
    piece: "R",
    title: "Fork #15",
    instruction: "Attack two pieces at once!",
    setup: "8/1b3k1p/p4P2/1p6/2n5/P6r/1P3R2/4R1K1 w - - 2 35",
    targets: [] as SquareId[],
    solution: ["e7", "b7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f7" as SquareId, to: "f8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-16",
    piece: "Q",
    title: "Fork #16",
    instruction: "Attack two pieces at once!",
    setup: "r4r2/ppq1ppkp/3p2p1/5P2/4b3/PP5P/2P1B1P1/R2Q1RK1 w - - 1 20",
    targets: [] as SquareId[],
    solution: ["d4", "e4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f7" as SquareId, to: "f6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-17",
    piece: "N",
    title: "Fork #17",
    instruction: "Attack two pieces at once!",
    setup: "r1b2rk1/ppp2ppp/6q1/3Nb3/3P4/5Q2/PPP3PP/R4RK1 w - - 0 16",
    targets: [] as SquareId[],
    solution: ["e7", "g6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g8" as SquareId, to: "h8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-18",
    piece: "N",
    title: "Fork #18",
    instruction: "Attack two pieces at once!",
    setup: "5b2/5k2/p1rpN1p1/1p6/1P2PB2/8/5KP1/8 w - - 0 49",
    targets: [] as SquareId[],
    solution: ["d8", "c6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-19",
    piece: "R",
    title: "Fork #19",
    instruction: "Attack two pieces at once!",
    setup: "1r3r1k/3b2b1/2n3q1/p1p4p/Pp2Pp2/1Q6/1PP1N1PR/2K4R w - - 0 28",
    targets: [] as SquareId[],
    solution: ["h5", "h6", "h6"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "g7" as SquareId, to: "h6" as SquareId }, { from: "g6" as SquareId, to: "h6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-fork-20",
    piece: "B",
    title: "Fork #20",
    instruction: "Attack two pieces at once!",
    setup: "8/p5pk/5p2/3Bp1p1/3b4/1P3KP1/2r2P1P/5R2 w - - 0 39",
    targets: [] as SquareId[],
    solution: ["e4", "c2"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g7" as SquareId, to: "g6" as SquareId }],
    strictSolution: true,
  },
];
