import type { Puzzle } from "./types";
import type { SquareId } from "../logic/types";

export const lichessRemovingDefenderPuzzles: Puzzle[] = [
  {
    id: "lichess-rtd-01",
    piece: "R",
    title: "Remove the Defender #1",
    instruction: "Capture the piece that guards the target!",
    setup: "5k2/1n3p2/p1b1rp1p/1p3p2/1P6/8/P4PPP/2R1R1K1 w - - 1 31",
    targets: [] as SquareId[],
    solution: ["e6", "c6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-02",
    piece: "R",
    title: "Remove the Defender #2",
    instruction: "Capture the piece that guards the target!",
    setup: "6k1/p4rp1/7p/3p4/1Pb1rPP1/4R1P1/7P/2R3K1 w - - 0 30",
    targets: [] as SquareId[],
    solution: ["e4", "c4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d5" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-03",
    piece: "R",
    title: "Remove the Defender #3",
    instruction: "Capture the piece that guards the target!",
    setup: "5rk1/1R3pp1/1b3r1p/8/1P5P/5RP1/5P2/6K1 w - - 1 37",
    targets: [] as SquareId[],
    solution: ["f6", "b6"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g7" as SquareId, to: "f6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-04",
    piece: "R",
    title: "Remove the Defender #4",
    instruction: "Capture the piece that guards the target!",
    setup: "3b2k1/2rb1ppp/4p3/N7/6n1/3R2P1/P3PP1P/2R3K1 w - - 0 25",
    targets: [] as SquareId[],
    solution: ["c7", "d7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d8" as SquareId, to: "c7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-05",
    piece: "R",
    title: "Remove the Defender #5",
    instruction: "Capture the piece that guards the target!",
    setup: "2br4/7k/p6p/6p1/2pBnr2/2P5/PP4PP/4RRK1 w - - 0 26",
    targets: [] as SquareId[],
    solution: ["f4", "e4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "g5" as SquareId, to: "f4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-06",
    piece: "R",
    title: "Remove the Defender #6",
    instruction: "Capture the piece that guards the target!",
    setup: "6k1/5pp1/p3p2p/3p4/nPr1bP2/P3R2P/6P1/2R3K1 w - - 0 29",
    targets: [] as SquareId[],
    solution: ["c4", "e4"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d5" as SquareId, to: "c4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-07",
    piece: "R",
    title: "Remove the Defender #7",
    instruction: "Capture the piece that guards the target!",
    setup: "2r3k1/p1rb1p1p/1p4p1/8/2RR4/1P2P3/P3BKPP/8 w - - 4 27",
    targets: [] as SquareId[],
    solution: ["d7", "c8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "c7" as SquareId, to: "d7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-08",
    piece: "R",
    title: "Remove the Defender #8",
    instruction: "Capture the piece that guards the target!",
    setup: "7k/pp1n2rp/2p5/8/1Pb1p3/P5R1/5P1P/3R2K1 w - - 0 40",
    targets: [] as SquareId[],
    solution: ["g7", "d7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "h8" as SquareId, to: "g7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-09",
    piece: "R",
    title: "Remove the Defender #9",
    instruction: "Capture the piece that guards the target!",
    setup: "8/3r3R/pnpp1kr1/1p2p3/8/1PP4P/P4PP1/3R2K1 w - - 10 33",
    targets: [] as SquareId[],
    solution: ["d7", "d6", "d7"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "b6" as SquareId, to: "d7" as SquareId }, { from: "f6" as SquareId, to: "f7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-10",
    piece: "R",
    title: "Remove the Defender #10",
    instruction: "Capture the piece that guards the target!",
    setup: "r7/p1r1k2p/1n2pp2/R2p2p1/B2P4/2P3P1/P4PP1/1R4K1 w - - 7 24",
    targets: [] as SquareId[],
    solution: ["b6", "a8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "a7" as SquareId, to: "b6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-11",
    piece: "R",
    title: "Remove the Defender #11",
    instruction: "Capture the piece that guards the target!",
    setup: "2r1k3/5p1R/p3pPp1/1p2P3/5PK1/3r4/P1p3P1/2R5 w - - 0 48",
    targets: [] as SquareId[],
    solution: ["h8", "c8", "c2"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "e8" as SquareId, to: "d7" as SquareId }, { from: "d7" as SquareId, to: "c8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-12",
    piece: "R",
    title: "Remove the Defender #12",
    instruction: "Capture the piece that guards the target!",
    setup: "rn2k2r/3pbp2/2b1p2p/4P3/2PP2p1/6P1/3N1PP1/RR2N1K1 w kq - 1 24",
    targets: [] as SquareId[],
    solution: ["a8", "b8"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "c6" as SquareId, to: "a8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-13",
    piece: "R",
    title: "Remove the Defender #13",
    instruction: "Capture the piece that guards the target!",
    setup: "Rn1r4/1p1k1pp1/4p2p/1N2P3/2P2r2/8/5P1P/2R3K1 w - - 4 25",
    targets: [] as SquareId[],
    solution: ["d1", "d8", "b8"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "d7" as SquareId, to: "e7" as SquareId }, { from: "e7" as SquareId, to: "d8" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-14",
    piece: "R",
    title: "Remove the Defender #14",
    instruction: "Capture the piece that guards the target!",
    setup: "4b1k1/R3Pr2/5b1p/2p3p1/2P5/3R2KP/1P6/8 w - - 1 39",
    targets: [] as SquareId[],
    solution: ["d8", "e7", "e8"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "f7" as SquareId, to: "e7" as SquareId }, { from: "f6" as SquareId, to: "e7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-15",
    piece: "R",
    title: "Remove the Defender #15",
    instruction: "Capture the piece that guards the target!",
    setup: "8/4bp2/r1p1k3/3pPp1r/1n1P4/1PR2N1P/6P1/R6K w - - 0 38",
    targets: [] as SquareId[],
    solution: ["a6", "c6", "a6"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "b4" as SquareId, to: "a6" as SquareId }, { from: "e6" as SquareId, to: "d7" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-16",
    piece: "R",
    title: "Remove the Defender #16",
    instruction: "Capture the piece that guards the target!",
    setup: "8/8/8/6R1/5r2/2P3p1/2KR4/5kr1 w - - 4 62",
    targets: [] as SquareId[],
    solution: ["d1", "g1", "g3"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "f1" as SquareId, to: "f2" as SquareId }, { from: "f2" as SquareId, to: "g1" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-17",
    piece: "R",
    title: "Remove the Defender #17",
    instruction: "Capture the piece that guards the target!",
    setup: "8/1p1r1p1k/p2p2pp/4n3/2r5/1NP5/PP3PPP/3RR1K1 w - - 2 30",
    targets: [] as SquareId[],
    solution: ["e5", "d7"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "d6" as SquareId, to: "e5" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-18",
    piece: "R",
    title: "Remove the Defender #18",
    instruction: "Capture the piece that guards the target!",
    setup: "5n1R/R7/p3kr2/1p1p2p1/6P1/1P4K1/P1n5/8 w - - 6 42",
    targets: [] as SquareId[],
    solution: ["a6", "f6", "f8"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "e6" as SquareId, to: "e5" as SquareId }, { from: "e5" as SquareId, to: "f6" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-19",
    piece: "B",
    title: "Remove the Defender #19",
    instruction: "Capture the piece that guards the target!",
    setup: "R7/5pkp/6p1/4n3/1P2r3/3B1b2/1B1b3P/5K2 w - - 0 42",
    targets: [] as SquareId[],
    solution: ["e4", "e5"] as SquareId[],
    starThresholds: { three: 2, two: 3, one: 4 },
    opponentResponses: [{ from: "f3" as SquareId, to: "e4" as SquareId }],
    strictSolution: true,
  },
  {
    id: "lichess-rtd-20",
    piece: "R",
    title: "Remove the Defender #20",
    instruction: "Capture the piece that guards the target!",
    setup: "8/8/3R4/8/8/KPk2r2/P1r1b2R/8 w - - 11 58",
    targets: [] as SquareId[],
    solution: ["c6", "c2", "e2"] as SquareId[],
    starThresholds: { three: 3, two: 4, one: 5 },
    opponentResponses: [{ from: "c3" as SquareId, to: "d3" as SquareId }, { from: "d3" as SquareId, to: "c2" as SquareId }],
    strictSolution: true,
  },
];
