import type { RoutePuzzle, FindMovesPuzzle } from "./types";

export const pawnPuzzles: (RoutePuzzle | FindMovesPuzzle)[] = [
  {
    type: "route",
    id: "pawn-01",
    playerPiece: "P",
    title: "First Step",
    instruction: "Move the pawn forward to the star!",
    position: [{ piece: "P", color: "w", square: "e2" }],
    walls: [],
    stars: ["e3"],
    hints: ["Pawns move forward one square.", "White pawns move up the board."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "pawn-02",
    playerPiece: "P",
    title: "Double Step",
    instruction: "Move the pawn two squares forward!",
    position: [{ piece: "P", color: "w", square: "e2" }],
    walls: [],
    stars: ["e4"],
    hints: ["From its starting position, a pawn can move two squares forward!", "This only works on the pawn's first move."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "pawn-03",
    playerPiece: "P",
    title: "One at a Time",
    instruction: "Walk the pawn to the star!",
    position: [{ piece: "P", color: "w", square: "d4" }],
    walls: [],
    stars: ["d6"],
    hints: ["The pawn has already moved, so it can only go one square at a time.", "The double-step only works from the starting rank."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "pawn-04",
    playerPiece: "P",
    title: "Diagonal Capture",
    instruction: "Capture the enemy piece!",
    position: [
      { piece: "P", color: "w", square: "d4" },
      { piece: "N", color: "b", square: "e5" },
    ],
    walls: [],
    stars: ["e5"],
    hints: ["Pawns capture diagonally, not straight ahead!", "Move one square diagonally forward."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "pawn-05",
    playerPiece: "P",
    title: "Can't Go Straight",
    instruction: "The path is blocked! Capture to get around.",
    position: [
      { piece: "P", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "d5" },
      { piece: "N", color: "b", square: "e5" },
    ],
    walls: [],
    stars: ["e5"],
    hints: ["Pawns can't move forward if a piece is in the way.", "But they CAN capture diagonally!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "pawn-06",
    playerPiece: "P",
    title: "Left or Right",
    instruction: "Capture the enemy piece!",
    position: [
      { piece: "P", color: "w", square: "d4" },
      { piece: "B", color: "b", square: "c5" },
    ],
    walls: [],
    stars: ["c5"],
    hints: ["Pawns can capture diagonally to the left too!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "pawn-07",
    playerPiece: "P",
    title: "March Forward",
    instruction: "March the pawn to the 8th rank!",
    position: [{ piece: "P", color: "w", square: "e2" }],
    walls: [],
    stars: ["e8"],
    hints: ["Use the double-step on the first move!", "Then one square at a time to the top."],
    starThresholds: { three: 5, two: 6, one: 7 },
  },
  {
    type: "route",
    id: "pawn-08",
    playerPiece: "P",
    title: "Capture Chain",
    instruction: "Capture both enemy pieces!",
    position: [
      { piece: "P", color: "w", square: "d4" },
      { piece: "N", color: "b", square: "e5" },
      { piece: "B", color: "b", square: "d6" },
    ],
    walls: [],
    stars: ["e5", "d6"],
    hints: ["Capture one diagonally, then capture the other.", "Zigzag through the enemies!"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "pawn-09",
    playerPiece: "P",
    title: "Blocked!",
    instruction: "The path forward is blocked. Find another way to the star!",
    position: [
      { piece: "P", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "d5" },
      { piece: "N", color: "b", square: "e5" },
      { piece: "B", color: "b", square: "f6" },
    ],
    walls: [],
    stars: ["f6"],
    hints: ["You can't go forward, but you can capture diagonally.", "Chain two diagonal captures together."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "pawn-10",
    playerPiece: "P",
    title: "Choose Your Capture",
    instruction: "Capture the right enemy to reach the star!",
    position: [
      { piece: "P", color: "w", square: "d4" },
      { piece: "N", color: "b", square: "c5" },
      { piece: "B", color: "b", square: "e5" },
    ],
    walls: [],
    stars: ["c5"],
    hints: ["The pawn can capture left or right.", "Which capture lands on the star?"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "pawn-11",
    playerPiece: "P",
    title: "Winding Path",
    instruction: "Zigzag through the enemies to the star!",
    position: [
      { piece: "P", color: "w", square: "d2" },
      { piece: "P", color: "w", square: "d3" },
      { piece: "N", color: "b", square: "e3" },
      { piece: "B", color: "b", square: "d4" },
      { piece: "R", color: "b", square: "e5" },
    ],
    walls: [],
    stars: ["e5"],
    hints: ["Capture diagonally each time.", "Left, right, left — zigzag up the board!"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "pawn-12",
    playerPiece: "P",
    title: "Promotion March",
    instruction: "Get the pawn to the 8th rank!",
    position: [
      { piece: "P", color: "w", square: "d5" },
      { piece: "P", color: "w", square: "d6" },
      { piece: "N", color: "b", square: "e6" },
      { piece: "B", color: "b", square: "d7" },
    ],
    walls: [],
    stars: ["d7"],
    hints: ["The forward path is blocked.", "Capture diagonally to get around, then capture again."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "pawn-13",
    playerPiece: "P",
    title: "Double Start",
    instruction: "Use the double-step, then capture to the star!",
    position: [
      { piece: "P", color: "w", square: "d2" },
      { piece: "N", color: "b", square: "e5" },
    ],
    walls: [],
    stars: ["e5"],
    hints: ["Start with a double-step to d4.", "Then capture diagonally to e5."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "pawn-14",
    playerPiece: "P",
    title: "Four Captures",
    instruction: "Capture all four enemy pieces!",
    position: [
      { piece: "P", color: "w", square: "e2" },
      { piece: "P", color: "b", square: "f3" },
      { piece: "N", color: "b", square: "e4" },
      { piece: "B", color: "b", square: "f5" },
      { piece: "R", color: "b", square: "e6" },
    ],
    walls: [],
    stars: ["f3", "e4", "f5", "e6"],
    hints: ["Zigzag diagonally through all four.", "Right, left, right, left!"],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "pawn-15",
    playerPiece: "P",
    title: "Pawn Master",
    instruction: "Capture all enemies and reach the 8th rank!",
    position: [
      { piece: "P", color: "w", square: "d2" },
      { piece: "N", color: "b", square: "e3" },
      { piece: "B", color: "b", square: "d4" },
      { piece: "R", color: "b", square: "e5" },
      { piece: "P", color: "b", square: "d6" },
      { piece: "N", color: "b", square: "e7" },
      { piece: "B", color: "b", square: "d8" },
    ],
    walls: [],
    stars: ["e3", "d4", "e5", "d6", "e7", "d8"],
    hints: ["Zigzag all the way to the top!", "Capture every enemy on the way."],
    starThresholds: { three: 6, two: 7, one: 8 },
  },
  // --- Find All Moves ---
  {
    type: "find-moves",
    id: "pawn-16",
    playerPiece: "P",
    title: "Find All Moves",
    instruction: "Click every square the pawn can move to!",
    position: [{ piece: "P", color: "w", square: "e2" }],
    walls: [],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
];
