import { Puzzle } from "./types";

export const queenPuzzles: Puzzle[] = [
  {
    id: "queen-01",
    piece: "Q",
    title: "Straight Line",
    instruction: "Move the queen to the star!",
    setup: [{ piece: "Q", color: "w", square: "d1" }],
    targets: ["d8"],
    solution: ["d8"],
    hints: ["The queen can move like a rook — in straight lines!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "queen-02",
    piece: "Q",
    title: "Diagonal",
    instruction: "Move the queen to the star!",
    setup: [{ piece: "Q", color: "w", square: "a1" }],
    targets: ["h8"],
    solution: ["h8"],
    hints: ["The queen can also move like a bishop — diagonally!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "queen-03",
    piece: "Q",
    title: "Pick a Direction",
    instruction: "Reach the star in 1 move!",
    setup: [{ piece: "Q", color: "w", square: "d4" }],
    targets: ["h8"],
    solution: ["h8"],
    hints: ["The queen can move diagonally any number of squares.", "d4 to h8 is one diagonal move."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "queen-04",
    piece: "Q",
    title: "Rook or Bishop?",
    instruction: "Reach the star — which way is faster?",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "d4" },
    ],
    targets: ["g7"],
    solution: ["a7", "g7"],
    hints: ["The diagonal is blocked by the pawn.", "Try combining a straight move with a diagonal."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "queen-05",
    piece: "Q",
    title: "Capture!",
    instruction: "Capture the enemy rook!",
    setup: [
      { piece: "Q", color: "w", square: "d1" },
      { piece: "R", color: "b", square: "d7" },
    ],
    targets: ["d7"],
    solution: ["d7"],
    hints: ["The queen captures by landing on the enemy's square."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "queen-06",
    piece: "Q",
    title: "Best Path",
    instruction: "Reach the star in the fewest moves!",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "b2" },
      { piece: "P", color: "w", square: "a5" },
    ],
    targets: ["h8"],
    solution: ["h1", "h8"],
    hints: ["The diagonal and the a-file are both partially blocked.", "Go sideways first, then straight up!"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "queen-07",
    piece: "Q",
    title: "Two Stars",
    instruction: "Reach both stars!",
    setup: [{ piece: "Q", color: "w", square: "d4" }],
    targets: ["d8", "h4"],
    solution: ["d8", "h4"],
    hints: ["The queen can reach each star in one move.", "Visit one, then the other."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "queen-08",
    piece: "Q",
    title: "Escape Artist",
    instruction: "Escape and reach the star!",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "b2" },
      { piece: "P", color: "w", square: "a3" },
    ],
    targets: ["h8"],
    solution: ["a2", "g8", "h8"],
    hints: ["The queen is almost boxed in.", "There's one square you can move to — find it, then think big."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "queen-09",
    piece: "Q",
    title: "Power Play",
    instruction: "Reach the star — use the queen's full power!",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "a4" },
    ],
    targets: ["g7"],
    solution: ["g1", "g7"],
    hints: ["Go sideways first to a clear file.", "Then go straight up."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "queen-10",
    piece: "Q",
    title: "Capture Spree",
    instruction: "Capture all three enemy pieces!",
    setup: [
      { piece: "Q", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "N", color: "b", square: "g7" },
      { piece: "B", color: "b", square: "g4" },
    ],
    targets: ["d7", "g7", "g4"],
    solution: ["d7", "g7", "g4"],
    hints: ["Plan a route that captures each one efficiently.", "The queen can switch between straight and diagonal."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "queen-11",
    piece: "Q",
    title: "Obstacle Course",
    instruction: "Navigate to the star!",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "c1" },
      { piece: "P", color: "w", square: "a3" },
      { piece: "P", color: "w", square: "c3" },
    ],
    targets: ["h8"],
    solution: ["a2", "g8", "h8"],
    hints: ["Find the one path out.", "a2 is reachable, then take a long diagonal."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "queen-12",
    piece: "Q",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    setup: [{ piece: "Q", color: "w", square: "d1" }],
    targets: ["d8", "h4", "a4"],
    solution: ["d8", "h4", "a4"],
    hints: ["The queen can reach d8 in one move, then use its flexibility.", "Switch between straight and diagonal movement."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "queen-13",
    piece: "Q",
    title: "Queen vs. Army",
    instruction: "Capture all four enemy pawns!",
    setup: [
      { piece: "Q", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "P", color: "b", square: "g4" },
      { piece: "P", color: "b", square: "a4" },
      { piece: "P", color: "b", square: "a1" },
    ],
    targets: ["d7", "g4", "a4", "a1"],
    solution: ["d7", "g4", "a4", "a1"],
    hints: ["Each capture sets up the next.", "Try going up first, then sweep around."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    id: "queen-14",
    piece: "Q",
    title: "Tight Maze",
    instruction: "Navigate to the star!",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "b2" },
      { piece: "P", color: "w", square: "c1" },
      { piece: "P", color: "w", square: "a3" },
    ],
    targets: ["h8"],
    solution: ["a2", "g8", "h8"],
    hints: ["The queen is almost boxed in.", "Find the one square you can move to, then think big."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "queen-15",
    piece: "Q",
    title: "Queen Master",
    instruction: "Capture all enemies and reach the star!",
    setup: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "R", color: "b", square: "a8" },
      { piece: "B", color: "b", square: "h1" },
      { piece: "P", color: "w", square: "d4" },
    ],
    targets: ["a8", "h1", "h8"],
    solution: ["a8", "h8", "h1"],
    hints: ["Capture the rook, then use the 8th rank.", "The queen's combined powers make this efficient."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
];
