import type { RoutePuzzle } from "./types";

export const queenPuzzles: RoutePuzzle[] = [
  {
    type: "route",
    id: "queen-01",
    playerPiece: "Q",
    title: "Straight Line",
    instruction: "Move the queen to the star!",
    position: [{ piece: "Q", color: "w", square: "d1" }],
    walls: [],
    stars: ["d8"],
    hints: ["The queen can move like a rook — in straight lines!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-02",
    playerPiece: "Q",
    title: "Diagonal",
    instruction: "Move the queen to the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: [],
    stars: ["h8"],
    hints: ["The queen can also move like a bishop — diagonally!"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-03",
    playerPiece: "Q",
    title: "Pick a Direction",
    instruction: "Reach the star in 1 move!",
    position: [{ piece: "Q", color: "w", square: "d4" }],
    walls: [],
    stars: ["h8"],
    hints: ["The queen can move diagonally any number of squares.", "d4 to h8 is one diagonal move."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-04",
    playerPiece: "Q",
    title: "Rook or Bishop?",
    instruction: "Reach the star — which way is faster?",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["d4"],
    stars: ["g7"],
    hints: ["The diagonal is blocked by the pawn.", "Try combining a straight move with a diagonal."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-05",
    playerPiece: "Q",
    title: "Capture!",
    instruction: "Capture the enemy rook!",
    position: [
      { piece: "Q", color: "w", square: "d1" },
      { piece: "R", color: "b", square: "d7" },
    ],
    walls: [],
    stars: ["d7"],
    hints: ["The queen captures by landing on the enemy's square."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-06",
    playerPiece: "Q",
    title: "Best Path",
    instruction: "Reach the star in the fewest moves!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["b2", "a5"],
    stars: ["h8"],
    hints: ["The diagonal and the a-file are both partially blocked.", "Go sideways first, then straight up!"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-07",
    playerPiece: "Q",
    title: "Two Stars",
    instruction: "Reach both stars!",
    position: [{ piece: "Q", color: "w", square: "d4" }],
    walls: [],
    stars: ["d8", "h4"],
    hints: ["The queen can reach each star in one move.", "Visit one, then the other."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-08",
    playerPiece: "Q",
    title: "Escape Artist",
    instruction: "Escape and reach the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["b2", "a3"],
    stars: ["h8"],
    hints: ["The queen is almost boxed in.", "There's one square you can move to — find it, then think big."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-09",
    playerPiece: "Q",
    title: "Power Play",
    instruction: "Reach the star — use the queen's full power!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["d4", "a4"],
    stars: ["g7"],
    hints: ["Go sideways first to a clear file.", "Then go straight up."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-10",
    playerPiece: "Q",
    title: "Capture Spree",
    instruction: "Capture all three enemy pieces!",
    position: [
      { piece: "Q", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "N", color: "b", square: "g7" },
      { piece: "B", color: "b", square: "g4" },
    ],
    walls: [],
    stars: ["d7", "g7", "g4"],
    hints: ["Plan a route that captures each one efficiently.", "The queen can switch between straight and diagonal."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-11",
    playerPiece: "Q",
    title: "Obstacle Course",
    instruction: "Navigate to the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["c1", "a3", "c3"],
    stars: ["h8"],
    hints: ["Find the one path out.", "a2 is reachable, then take a long diagonal."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-12",
    playerPiece: "Q",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    position: [{ piece: "Q", color: "w", square: "d1" }],
    walls: [],
    stars: ["d8", "h4", "a4"],
    hints: ["The queen can reach d8 in one move, then use its flexibility.", "Switch between straight and diagonal movement."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-13",
    playerPiece: "Q",
    title: "Queen vs. Army",
    instruction: "Capture all four enemy pawns!",
    position: [
      { piece: "Q", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "P", color: "b", square: "g4" },
      { piece: "P", color: "b", square: "a4" },
      { piece: "P", color: "b", square: "a1" },
    ],
    walls: [],
    stars: ["d7", "g4", "a4", "a1"],
    hints: ["Each capture sets up the next.", "Try going up first, then sweep around."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "queen-14",
    playerPiece: "Q",
    title: "Tight Maze",
    instruction: "Navigate to the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["b2", "c1", "a3"],
    stars: ["h8"],
    hints: ["The queen is almost boxed in.", "Find the one square you can move to, then think big."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-15",
    playerPiece: "Q",
    title: "Queen Master",
    instruction: "Capture all enemies and reach the star!",
    position: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "R", color: "b", square: "a8" },
      { piece: "B", color: "b", square: "h1" },
    ],
    walls: ["d4"],
    stars: ["a8", "h1", "h8"],
    hints: ["Capture the rook, then use the 8th rank.", "The queen's combined powers make this efficient."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
];
