import type { RoutePuzzle, FindMovesPuzzle } from "./types";

export const queenPuzzles: (RoutePuzzle | FindMovesPuzzle)[] = [
  {
    type: "route",
    id: "queen-01",
    playerPiece: "Q",
    title: "Straight Line",
    instruction: "Move the queen to the star!",
    position: [{ piece: "Q", color: "w", square: "d1" }],
    walls: [],
    stars: ["d8"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-02",
    playerPiece: "Q",
    title: "Diagonal",
    instruction: "Move the queen to the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: [],
    stars: ["h8"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-03",
    playerPiece: "Q",
    title: "Pick a Direction",
    instruction: "Reach the star in 1 move!",
    position: [{ piece: "Q", color: "w", square: "d4" }],
    walls: [],
    stars: ["h8"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-04",
    playerPiece: "Q",
    title: "Rook or Bishop?",
    instruction: "Reach the star — which way is faster?",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["d4"],
    stars: ["g7"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-05",
    playerPiece: "Q",
    title: "Capture!",
    instruction: "Capture the enemy rook!",
    position: [
      { piece: "Q", color: "w", square: "d1" },
      { piece: "R", color: "b", square: "d7" },
    ],
    walls: [],
    stars: ["d7"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "queen-06",
    playerPiece: "Q",
    title: "Best Path",
    instruction: "Reach the star in the fewest moves!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["b2", "a5"],
    stars: ["h8"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-07",
    playerPiece: "Q",
    title: "Two Stars",
    instruction: "Reach both stars!",
    position: [{ piece: "Q", color: "w", square: "d4" }],
    walls: [],
    stars: ["d8", "h4"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-08",
    playerPiece: "Q",
    title: "Escape Artist",
    instruction: "Escape and reach the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["b2", "a3", "h1"],
    stars: ["h8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-09",
    playerPiece: "Q",
    title: "Power Play",
    instruction: "Reach the star — use the queen's full power!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["d4", "a4"],
    stars: ["g7"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "queen-10",
    playerPiece: "Q",
    title: "Capture Spree",
    instruction: "Capture all three enemy pieces!",
    position: [
      { piece: "Q", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "N", color: "b", square: "g7" },
      { piece: "B", color: "b", square: "g4" },
    ],
    walls: [],
    stars: ["d7", "g7", "g4"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-11",
    playerPiece: "Q",
    title: "Obstacle Course",
    instruction: "Navigate to the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["c1", "a3", "c3"],
    stars: ["h8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-12",
    playerPiece: "Q",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    position: [{ piece: "Q", color: "w", square: "d1" }],
    walls: [],
    stars: ["d8", "h4", "a4"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-13",
    playerPiece: "Q",
    title: "Queen vs. Army",
    instruction: "Capture all four enemy pieces!",
    position: [
      { piece: "Q", color: "w", square: "d4" },
      { piece: "P", color: "b", square: "d7" },
      { piece: "P", color: "b", square: "g4" },
      { piece: "P", color: "b", square: "a4" },
      { piece: "R", color: "b", square: "a1" },
    ],
    walls: [],
    stars: ["d7", "g4", "a4", "a1"],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "queen-14",
    playerPiece: "Q",
    title: "Tight Maze",
    instruction: "Navigate to the star!",
    position: [{ piece: "Q", color: "w", square: "a1" }],
    walls: ["b2", "c1", "a3"],
    stars: ["h8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "queen-15",
    playerPiece: "Q",
    title: "Queen Master",
    instruction: "Capture all enemies and reach the star!",
    position: [
      { piece: "Q", color: "w", square: "a1" },
      { piece: "R", color: "b", square: "a8" },
      { piece: "B", color: "b", square: "h1" },
    ],
    walls: ["d4"],
    stars: ["a8", "h1", "h8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  // --- Find All Moves ---
  {
    type: "find-moves",
    id: "queen-16",
    playerPiece: "Q",
    title: "Find All Moves",
    instruction: "Click every square the queen can move to!",
    showHow: true,
    position: [{ piece: "Q", color: "w", square: "d5" }],
    walls: ["b5", "d2", "f7"],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
];
