import type { RoutePuzzle, FindMovesPuzzle } from "./types";

export const rookPuzzles: (RoutePuzzle | FindMovesPuzzle)[] = [
  {
    type: "route",
    id: "rook-01",
    playerPiece: "R",
    title: "Straight Ahead",
    instruction: "Move the rook to the star!",
    position: [{ piece: "R", color: "w", square: "d1" }],
    walls: [],
    stars: ["d8"],
    hints: ["The rook moves in straight lines.", "Move up the file to row 8."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "rook-02",
    playerPiece: "R",
    title: "Side to Side",
    instruction: "Move the rook to the star!",
    position: [{ piece: "R", color: "w", square: "a4" }],
    walls: [],
    stars: ["h4"],
    hints: ["The rook can also move along ranks (sideways)."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "rook-03",
    playerPiece: "R",
    title: "Turn the Corner",
    instruction: "Reach the star in 2 moves!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: [],
    stars: ["h8"],
    hints: ["The rook can't move diagonally.", "Go up first, then across (or across then up)."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "rook-04",
    playerPiece: "R",
    title: "Around the Wall",
    instruction: "Navigate around the obstacle to reach the star!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["a4", "b1"],
    stars: ["a8"],
    hints: ["The rook is blocked by pieces.", "Move up, then go around the pawn."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "rook-05",
    playerPiece: "R",
    title: "Capture!",
    instruction: "Capture the enemy knight!",
    position: [
      { piece: "R", color: "w", square: "e1" },
      { piece: "N", color: "b", square: "e7" },
    ],
    walls: [],
    stars: ["e7"],
    hints: ["The rook captures by moving to a square with an enemy piece."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "rook-06",
    playerPiece: "R",
    title: "Choose Your Path",
    instruction: "Reach the star in the fewest moves!",
    position: [{ piece: "R", color: "w", square: "d4" }],
    walls: ["d6", "f4"],
    stars: ["h8"],
    hints: ["You need to go around the obstacles.", "Try moving up first."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-07",
    playerPiece: "R",
    title: "Two Stars",
    instruction: "Reach both stars!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: [],
    stars: ["a8", "h1"],
    hints: ["Visit one star, then navigate to the other.", "Try the top one first."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-08",
    playerPiece: "R",
    title: "Maze Runner",
    instruction: "Navigate through the pawns to reach the star!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["c1", "a3", "c3", "e2"],
    stars: ["e4"],
    hints: ["Find the gaps between the pawns.", "The b-file has a clear path upward."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-09",
    playerPiece: "R",
    title: "Capture and Continue",
    instruction: "Capture the enemy bishop, then reach the star!",
    position: [
      { piece: "R", color: "w", square: "h1" },
      { piece: "B", color: "b", square: "h5" },
    ],
    walls: [],
    stars: ["h5", "a5"],
    hints: ["Capture the bishop first — it's on your way!", "Then slide across the rank."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "rook-10",
    playerPiece: "R",
    title: "The Long Way Around",
    instruction: "Reach the star — but the direct path is blocked!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["a5", "d1"],
    stars: ["a8"],
    hints: [
      "You can't go straight up — there's a pawn blocking a5.",
      "Go right first, then up, then back over to the a-file."
    ],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-11",
    playerPiece: "R",
    title: "Express Lane",
    instruction: "Reach the star as efficiently as possible!",
    position: [{ piece: "R", color: "w", square: "d1" }],
    walls: ["d5", "g1"],
    stars: ["g8"],
    hints: ["Go up, then over, then up again.", "Stop before the pawn on d5."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-12",
    playerPiece: "R",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    position: [{ piece: "R", color: "w", square: "e4" }],
    walls: [],
    stars: ["a4", "e8", "h4"],
    hints: ["Plan a route that visits all three efficiently.", "You can visit them in any order."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "rook-13",
    playerPiece: "R",
    title: "Cleanup Crew",
    instruction: "Capture both enemy pawns!",
    position: [
      { piece: "R", color: "w", square: "d1" },
      { piece: "P", color: "b", square: "d5" },
      { piece: "P", color: "b", square: "h5" },
    ],
    walls: [],
    stars: ["d5", "h5"],
    hints: ["Capture them one at a time.", "The first one is directly above you."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "rook-14",
    playerPiece: "R",
    title: "Zigzag",
    instruction: "Navigate the zigzag to the star!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["b1", "a4", "c4", "b7"],
    stars: ["c8"],
    hints: ["Move up, then right, then up, then right...", "Use the gaps in the pawn wall."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "rook-15",
    playerPiece: "R",
    title: "Rook Master",
    instruction: "Capture both enemy pieces!",
    position: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "N", color: "b", square: "a6" },
      { piece: "B", color: "b", square: "f6" },
    ],
    walls: [],
    stars: ["a6", "f6"],
    hints: ["Capture the knight first.", "Then slide over to capture the bishop on the star."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  // --- Find All Moves (3-step scaffolding: demo → guided → test) ---
  {
    type: "find-moves",
    id: "rook-16",
    playerPiece: "R",
    title: "Watch the Rook",
    instruction: "Watch where the rook can go!",
    mode: "demo",
    position: [{ piece: "R", color: "w", square: "e4" }],
    walls: [],
    starThresholds: { three: 0, two: 0, one: 0 },
  },
  {
    type: "find-moves",
    id: "rook-17",
    playerPiece: "R",
    title: "Tap the Green Squares",
    instruction: "Tap every green square!",
    mode: "guided",
    position: [{ piece: "R", color: "w", square: "d4" }],
    walls: ["d7"],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
  {
    type: "find-moves",
    id: "rook-18",
    playerPiece: "R",
    title: "Find All Moves",
    instruction: "Tap every square the rook can move to!",
    mode: "test",
    position: [{ piece: "R", color: "w", square: "d4" }],
    walls: ["b4", "d7"],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
];
