import type { RoutePuzzle, FindMovesPuzzle } from "./types";

export const rookPuzzles: (RoutePuzzle | FindMovesPuzzle)[] = [
  {
    type: "route",
    id: "rook-01",
    playerPiece: "R",
    title: "Straight Ahead",
    instruction: "Move the rook to the star!",
    position: [{ piece: "R", color: "w", square: "d1" }],
    walls: [],
    stars: ["d8"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "rook-02",
    playerPiece: "R",
    title: "Side to Side",
    instruction: "Move the rook to the star!",
    position: [{ piece: "R", color: "w", square: "a4" }],
    walls: [],
    stars: ["h4"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "rook-03",
    playerPiece: "R",
    title: "Turn the Corner",
    instruction: "Reach the star in 2 moves!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: [],
    stars: ["h8"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "rook-04",
    playerPiece: "R",
    title: "Around the Wall",
    instruction: "Navigate around the obstacle to reach the star!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["a4", "b1"],
    stars: ["a8"],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "rook-05",
    playerPiece: "R",
    title: "Capture!",
    instruction: "Capture the enemy knight!",
    position: [
      { piece: "R", color: "w", square: "e1" },
      { piece: "N", color: "b", square: "e7" },
    ],
    walls: [],
    stars: ["e7"],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    type: "route",
    id: "rook-06",
    playerPiece: "R",
    title: "Choose Your Path",
    instruction: "Reach the star in the fewest moves!",
    position: [{ piece: "R", color: "w", square: "d4" }],
    walls: ["d6", "f4"],
    stars: ["h8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-07",
    playerPiece: "R",
    title: "Two Stars",
    instruction: "Reach both stars!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: [],
    stars: ["a8", "h1"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-08",
    playerPiece: "R",
    title: "Maze Runner",
    instruction: "Navigate through the pawns to reach the star!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["c1", "a3", "c3", "e2"],
    stars: ["e4"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-09",
    playerPiece: "R",
    title: "Capture and Continue",
    instruction: "Capture the enemy bishop, then reach the star!",
    position: [
      { piece: "R", color: "w", square: "h1" },
      { piece: "B", color: "b", square: "h5" },
    ],
    walls: [],
    stars: ["h5", "a5"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "rook-10",
    playerPiece: "R",
    title: "The Long Way Around",
    instruction: "Reach the star — but the direct path is blocked!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["a5", "d1"],
    stars: ["a8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-11",
    playerPiece: "R",
    title: "Express Lane",
    instruction: "Reach the star as efficiently as possible!",
    position: [{ piece: "R", color: "w", square: "d1" }],
    walls: ["d5", "g1"],
    stars: ["g8"],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    type: "route",
    id: "rook-12",
    playerPiece: "R",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    position: [{ piece: "R", color: "w", square: "e4" }],
    walls: [],
    stars: ["a4", "e8", "h4"],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "rook-13",
    playerPiece: "R",
    title: "Cleanup Crew",
    instruction: "Capture both enemy pawns!",
    position: [
      { piece: "R", color: "w", square: "d1" },
      { piece: "P", color: "b", square: "d5" },
      { piece: "P", color: "b", square: "h5" },
    ],
    walls: [],
    stars: ["d5", "h5"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    type: "route",
    id: "rook-14",
    playerPiece: "R",
    title: "Zigzag",
    instruction: "Navigate the zigzag to the star!",
    position: [{ piece: "R", color: "w", square: "a1" }],
    walls: ["b1", "a4", "c4", "b7"],
    stars: ["c8"],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    type: "route",
    id: "rook-15",
    playerPiece: "R",
    title: "Rook Master",
    instruction: "Capture both enemy pieces!",
    position: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "N", color: "b", square: "a6" },
      { piece: "B", color: "b", square: "f6" },
    ],
    walls: [],
    stars: ["a6", "f6"],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  // --- Find All Moves (3-step scaffolding: demo → guided → test) ---
  {
    type: "find-moves",
    id: "rook-16",
    playerPiece: "R",
    title: "Find the Moves",
    instruction: "Tap every square the rook can move to!",
    mode: "test",
    position: [{ piece: "R", color: "w", square: "e4" }],
    walls: [],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
  {
    type: "find-moves",
    id: "rook-17",
    playerPiece: "R",
    title: "Find the Moves",
    instruction: "Tap every square the rook can move to!",
    mode: "guided",
    position: [{ piece: "R", color: "w", square: "d4" }],
    walls: ["d7"],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
  {
    type: "find-moves",
    id: "rook-18",
    playerPiece: "R",
    title: "Find All Moves",
    instruction: "Tap every square the rook can move to!",
    mode: "test",
    position: [{ piece: "R", color: "w", square: "d4" }],
    walls: ["b4", "d7"],
    starThresholds: { three: 0, two: 2, one: 4 },
  },
];
