import { Puzzle } from "./types";

export const rookPuzzles: Puzzle[] = [
  {
    id: "rook-01",
    piece: "R",
    title: "Straight Ahead",
    instruction: "Move the rook to the star!",
    setup: [{ piece: "R", color: "w", square: "d1" }],
    targets: ["d8"],
    solution: ["d8"],
    maxMoves: 1,
    hints: ["The rook moves in straight lines.", "Move up the file to row 8."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "rook-02",
    piece: "R",
    title: "Side to Side",
    instruction: "Move the rook to the star!",
    setup: [{ piece: "R", color: "w", square: "a4" }],
    targets: ["h4"],
    solution: ["h4"],
    maxMoves: 1,
    hints: ["The rook can also move along ranks (sideways)."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "rook-03",
    piece: "R",
    title: "Turn the Corner",
    instruction: "Reach the star in 2 moves!",
    setup: [{ piece: "R", color: "w", square: "a1" }],
    targets: ["h8"],
    solution: ["a8", "h8"],
    maxMoves: 3,
    hints: ["The rook can't move diagonally.", "Go up first, then across (or across then up)."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "rook-04",
    piece: "R",
    title: "Around the Wall",
    instruction: "Navigate around the obstacle to reach the star!",
    setup: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "a4" },
      { piece: "P", color: "w", square: "b1" },
    ],
    targets: ["a8"],
    solution: ["a3", "b3", "b8", "a8"],
    maxMoves: 5,
    hints: ["The rook is blocked by pieces.", "Move up, then go around the pawn."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    id: "rook-05",
    piece: "R",
    title: "Capture!",
    instruction: "Capture the enemy knight!",
    setup: [
      { piece: "R", color: "w", square: "e1" },
      { piece: "N", color: "b", square: "e7" },
    ],
    targets: ["e7"],
    solution: ["e7"],
    maxMoves: 1,
    hints: ["The rook captures by moving to a square with an enemy piece."],
    starThresholds: { three: 1, two: 2, one: 3 },
  },
  {
    id: "rook-06",
    piece: "R",
    title: "Choose Your Path",
    instruction: "Reach the star in the fewest moves!",
    setup: [
      { piece: "R", color: "w", square: "d4" },
      { piece: "P", color: "w", square: "d6" },
      { piece: "P", color: "w", square: "f4" },
    ],
    targets: ["h8"],
    solution: ["d5", "h5", "h8"],
    maxMoves: 4,
    hints: ["You need to go around the obstacles.", "Try moving up first."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "rook-07",
    piece: "R",
    title: "Two Stars",
    instruction: "Reach both stars!",
    setup: [{ piece: "R", color: "w", square: "a1" }],
    targets: ["a8", "h1"],
    solution: ["a8", "h8", "h1"],
    maxMoves: 4,
    hints: ["Visit one star, then navigate to the other.", "Try the top one first."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "rook-08",
    piece: "R",
    title: "Maze Runner",
    instruction: "Navigate through the pawns to reach the star!",
    setup: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "c1" },
      { piece: "P", color: "w", square: "a3" },
      { piece: "P", color: "w", square: "c3" },
      { piece: "P", color: "w", square: "e2" },
    ],
    targets: ["e4"],
    solution: ["b1", "b4", "e4"],
    maxMoves: 4,
    hints: ["Find the gaps between the pawns.", "The b-file has a clear path upward."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "rook-09",
    piece: "R",
    title: "Capture and Continue",
    instruction: "Capture the enemy bishop, then reach the star!",
    setup: [
      { piece: "R", color: "w", square: "h1" },
      { piece: "B", color: "b", square: "h5" },
    ],
    targets: ["h5", "a5"],
    solution: ["h5", "a5"],
    maxMoves: 3,
    hints: ["Capture the bishop first — it's on your way!", "Then slide across the rank."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "rook-10",
    piece: "R",
    title: "The Long Way Around",
    instruction: "Reach the star — but the direct path is blocked!",
    setup: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "a5" },
      { piece: "P", color: "w", square: "d1" },
    ],
    targets: ["a8"],
    solution: ["c1", "c8", "a8"],
    maxMoves: 4,
    hints: [
      "You can't go straight up — there's a pawn blocking a5.",
      "Go right first, then up, then back over to the a-file."
    ],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "rook-11",
    piece: "R",
    title: "Express Lane",
    instruction: "Reach the star as efficiently as possible!",
    setup: [
      { piece: "R", color: "w", square: "d1" },
      { piece: "P", color: "w", square: "d5" },
      { piece: "P", color: "w", square: "g1" },
    ],
    targets: ["g8"],
    solution: ["d4", "g4", "g8"],
    maxMoves: 4,
    hints: ["Go up, then over, then up again.", "Stop before the pawn on d5."],
    starThresholds: { three: 3, two: 4, one: 5 },
  },
  {
    id: "rook-12",
    piece: "R",
    title: "Three Stars",
    instruction: "Reach all three stars!",
    setup: [{ piece: "R", color: "w", square: "e4" }],
    targets: ["a4", "e8", "h4"],
    solution: ["e8", "h8", "h4", "a4"],
    maxMoves: 6,
    hints: ["Plan a route that visits all three efficiently.", "You can visit them in any order."],
    starThresholds: { three: 4, two: 5, one: 6 },
  },
  {
    id: "rook-13",
    piece: "R",
    title: "Cleanup Crew",
    instruction: "Capture both enemy pawns!",
    setup: [
      { piece: "R", color: "w", square: "d1" },
      { piece: "P", color: "b", square: "d5" },
      { piece: "P", color: "b", square: "h5" },
    ],
    targets: ["d5", "h5"],
    solution: ["d5", "h5"],
    maxMoves: 3,
    hints: ["Capture them one at a time.", "The first one is directly above you."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
  {
    id: "rook-14",
    piece: "R",
    title: "Zigzag",
    instruction: "Navigate the zigzag to the star!",
    setup: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "P", color: "w", square: "b1" },
      { piece: "P", color: "w", square: "a4" },
      { piece: "P", color: "w", square: "c4" },
      { piece: "P", color: "w", square: "b7" },
    ],
    targets: ["c8"],
    solution: ["a3", "b3", "b6", "c6", "c8"],
    maxMoves: 6,
    hints: ["Move up, then right, then up, then right...", "Use the gaps in the pawn wall."],
    starThresholds: { three: 5, two: 6, one: 7 },
  },
  {
    id: "rook-15",
    piece: "R",
    title: "Rook Master",
    instruction: "Capture both enemy pieces!",
    setup: [
      { piece: "R", color: "w", square: "a1" },
      { piece: "N", color: "b", square: "a6" },
      { piece: "B", color: "b", square: "f6" },
    ],
    targets: ["a6", "f6"],
    solution: ["a6", "f6"],
    maxMoves: 3,
    hints: ["Capture the knight first.", "Then slide over to capture the bishop on the star."],
    starThresholds: { three: 2, two: 3, one: 4 },
  },
];
